### ISSUE TITLE
Migration App not working after restart

### ISSUE THREAD

**Issue by CowboyNick** [OracleSiebel/ConfiguringSiebel#103]
Hello,

After deploying the application on Siebel 20.11, I can then deploy the migration application and login fine. However, removing the containers and re-deploying them I get the error "Unable to process the request. Application configuration does not exist." when trying to login to the migration application. When checking in Chorme DevTools, it looks like the URL https://<hostname>/siebel/migration/Login is returning: {"status":"error","msg":"INTL_MISSING_CONFIG"}. If I delete and re-deploy the migration application in SMC, everything works again. I have found that if I restart everything except the cgw container, everything works fine. It only happens when I stop all containers including the cgw. I have verified the persistence file lists for cgw, ses and sai match what you have. I'm not sure where to look next or where this error is coming from.

Thanks,

-Nick

**Comment by OracleSiebel** [comment]
The most likely reason is that there's a file missing from the persistence definition. You might be able to identify it by doing a diff on the cgw container before you configure migration, and then another diff after migration. This should help identify the file required to persist the migration definition.

**Comment by CowboyNick** [comment]
This appears to be caused by bug identified in DocID [2444510.1](https://support.oracle.com/epmos/faces/DocContentDisplay?id=2444510.1). Closing and will wait for fix in future update.
