### ISSUE TITLE
Write access check failed for folder

### ISSUE THREAD

**Issue by sunkugupta** [OracleSiebel/ConfiguringSiebel#105]
Hello,

We are unable to launch container form build-mde. Below is the error log

{"log":"+ bash /config/kernelCheck\r\n","stream":"stdout","time":"2021-03-28T18:37:48.603105372Z"}
{"log":"The current kernel version is: 3.10.0-1160.15.2.el7.x86_64\r\n","stream":"stdout","time":"2021-03-28T18:37:48.624099947Z"}
{"log":"Kernel test passed\r\n","stream":"stdout","time":"2021-03-28T18:37:48.624138442Z"}
{"log":"+ '[' '!' 0 -eq 0 ']'\r\n","stream":"stdout","time":"2021-03-28T18:37:48.627727081Z"}
{"log":"+ persistencePath=/persistent\r\n","stream":"stdout","time":"2021-03-28T18:37:48.627757651Z"}
{"log":"+ '[' '!' -z ']'\r\n","stream":"stdout","time":"2021-03-28T18:37:48.627766517Z"}
{"log":"+ sfsPath=/sfs\r\n","stream":"stdout","time":"2021-03-28T18:37:48.627774535Z"}
{"log":"+ sourcePath=/siebel/mde\r\n","stream":"stdout","time":"2021-03-28T18:37:48.627781751Z"}
{"log":"+ bash /config/pvCheck /persistent /sfs\r\n","stream":"stdout","time":"2021-03-28T18:37:48.627789455Z"}
{"log":"touch: cannot touch ‘/persistent/pvtest’: Permission denied\r\n","stream":"stdout","time":"2021-03-28T18:37:48.648278039Z"}
{"log":"Write access check failed for folder --\u003e /persistent \r\n","stream":"stdout","time":"2021-03-28T18:37:48.648607151Z"}
{"log":"Please make sure that the persistent folder is owned on your host by the same userid:groupid as the one used to launch the container.\r\n","stream":"stdout","time":"2021-03-28T18:37:48.648624641Z"}
{"log":"If you have selinux disabled also check that the dockerd option '--selinux-enabled' is disabled \r\n","stream":"stdout","time":"2021-03-28T18:37:48.648632482Z"}
{"log":" in file /etc/sysconfig/docker .\r\n","stream":"stdout","time":"2021-03-28T18:37:48.648639286Z"}
{"log":"touch: cannot touch ‘/sfs/pvtest’: Permission denied\r\n","stream":"stdout","time":"2021-03-28T18:37:48.650466631Z"}
{"log":"Write access check failed for folder --\u003e /sfs \r\n","stream":"stdout","time":"2021-03-28T18:37:48.650934849Z"}
{"log":"Please make sure that the persistent folder is owned on your host by the same userid:groupid as the one used to launch the container.\r\n","stream":"stdout","time":"2021-03-28T18:37:48.650950558Z"}
{"log":"If you have selinux disabled also check that the dockerd option '--selinux-enabled' is disabled \r\n","stream":"stdout","time":"2021-03-28T18:37:48.6509575Z"}
{"log":" in file /etc/sysconfig/docker .\r\n","stream":"stdout","time":"2021-03-28T18:37:48.650963896Z"}
{"log":"+ '[' '!' 1 -eq 0 ']'\r\n","stream":"stdout","time":"2021-03-28T18:37:48.651364736Z"}
{"log":"+ exit 1\r\n","stream":"stdout","time":"2021-03-28T18:37:48.65138037Z"}

**Comment by OracleSiebel** [comment]
Hi,

The most obvious issue is right here in the log you've supplied:

touch: cannot touch ‘/persistent/pvtest’: Permission denied

When you launch the containers, if you are using the scripts supplied, you will have defined the location for persistent volumes:

https://github.com/OracleSiebel/ConfiguringSiebel/blob/master/Containerization/Docker/oraclelinux/classic-mde/manage/scripts/automate-architecture/launch-siebel/sample-architecture.sh#L2

This location should be writable by the user you are specifying to launch the containers:

https://github.com/OracleSiebel/ConfiguringSiebel/blob/master/Containerization/Docker/oraclelinux/classic-mde/manage/scripts/automate-architecture/launch-siebel/sample-architecture.sh#L19

In this folder you should have four folders; SES, CGW, SAI, and SFS, again all writable by the above user.

**Comment by sunkugupta** [comment]
Thanks. I resolved the above error. However, i am now seeing a lot of "Permission Denied" errors 

{"log":"+ ln -s /persistent/applicationcontainer_external/webapps/applicationinterface.properties /siebel/mde/applicationcontainer_external/webapps/applicationinterface.properties\r\n","stream":"stdout","time":"2021-03-29T18:24:28.266290383Z"}
{"log":"ln: failed to create symbolic link ‘/siebel/mde/applicationcontainer_external/webapps/applicationinterface.properties’: File exists\r\n","stream":"stdout","time":"2021-03-29T18:24:28.267299236Z"}
{"log":"+ for file in '${fileList[@]}'\r\n","stream":"stdout","time":"2021-03-29T18:24:28.26731655Z"}
{"log":"++ dirname /applicationcontainer_external/webapps/migration.properties\r\n","stream":"stdout","time":"2021-03-29T18:24:28.268431685Z"}
{"log":"+ folder=/applicationcontainer_external/webapps\r\n","stream":"stdout","time":"2021-03-29T18:24:28.268777619Z"}
{"log":"+ '[' '!' -f /persistent/applicationcontainer_external/webapps/migration.properties ']'\r\n","stream":"stdout","time":"2021-03-29T18:24:28.268792163Z"}
{"log":"+ mkdir -p /persistent/applicationcontainer_external/webapps\r\n","stream":"stdout","time":"2021-03-29T18:24:28.268799577Z"}
{"log":"+ mv /siebel/mde/applicationcontainer_external/webapps/migration.properties /persistent/applicationcontainer_external/webapps\r\n","stream":"stdout","time":"2021-03-29T18:24:28.270131134Z"}
{"log":"mv: cannot remove ‘/siebel/mde/applicationcontainer_external/webapps/migration.properties’: Permission denied\r\n","stream":"stdout","time":"2021-03-29T18:24:28.27603985Z"}
{"log":"+ rm -f /siebel/mde/applicationcontainer_external/webapps/migration.properties\r\n","stream":"stdout","time":"2021-03-29T18:24:28.276339913Z"}
{"log":"rm: cannot remove ‘/siebel/mde/applicationcontainer_external/webapps/migration.properties’: Permission denied\r\n","stream":"stdout","time":"2021-03-29T18:24:28.277419571Z"}
{"log":"+ ln -s /persistent/applicationcontainer_external/webapps/migration.properties /siebel/mde/applicationcontainer_external/webapps/migration.properties\r\n","stream":"stdout","time":"2021-03-29T18:24:28.277435519Z"}
{"log":"ln: failed to create symbolic link ‘/siebel/mde/applicationcontainer_external/webapps/migration.properties’: File exists\r\n","stream":"stdout","time":"2021-03-29T18:24:28.278363738Z"}
{"log":"+ for file in '${fileList[@]}'\r\n","stream":"stdout","time":"2021-03-29T18:24:28.278883829Z"}
{"log":"++ dirname /applicationcontainer_external/webapps/GatewayServiceFramework.log\r\n","stream":"stdout","time":"2021-03-29T18:24:28.278897945Z"}
{"log":"+ folder=/applicationcontainer_external/webapps\r\n","stream":"stdout","time":"2021-03-29T18:24:28.279846829Z"}
{"log":"+ '[' '!' -f /persistent/applicationcontainer_external/webapps/GatewayServiceFramework.log ']'\r\n","stream":"stdout","time":"2021-03-29T18:24:28.27986193Z"}
{"log":"+ mkdir -p /persistent/applicationcontainer_external/webapps\r\n","stream":"stdout","time":"2021-03-29T18:24:28.279869649Z"}
{"log":"+ mv /siebel/mde/applicationcontainer_external/webapps/GatewayServiceFramework.log /persistent/applicationcontainer_external/webapps\r\n","stream":"stdout","time":"2021-03-29T18:24:28.281225473Z"}

**Comment by sunkugupta** [comment]
Any update on this please or should i open another ticket?

**Comment by OracleSiebel** [comment]
This is still some sort of permission issue with the way you are launching the containers. Here's an error you have:

{"log":"+ rm -f /siebel/mde/applicationcontainer_external/webapps/migration.properties\r\n","stream":"stdout","time":"2021-03-29T18:24:28.276339913Z"}
{"log":"rm: cannot remove ‘/siebel/mde/applicationcontainer_external/webapps/migration.properties’: Permission denied\r\n","stream":"stdout","time":"2021-03-29T18:24:28.277419571Z"}

Have you used docker exec to go into the container and attempt the operation manually? This might reveal your issue and lead you to a solution.

It's no good simply supplying a log. If you want help, you'll need to supply much more detail. Perhaps a build log from multi-stage/build and persistence/build would help. What OS are you using? What's in your architecture.sh file?

**Comment by sunkugupta** [comment]
got it resolved. Had incorrect iuser, group in the files.

**Comment by OracleSiebel** [comment]
Good to hear. Thanks for closing the issue.
