### ISSUE TITLE
JSON parameters for signglesignon, trusttoketn

### ISSUE THREAD

**Issue by sunkugupta** [OracleSiebel/ConfiguringSiebel#111]
Hi duncan

I need to add additional parameters in createSAI file for enabling singlesignon. Where can i find the corresponding json parameters for trusttoken, user specification etc

thanks
Sunku

**Comment by OracleSiebel** [comment]
That should be configured during SMC configuration, and not part of the build process. Any configuration you do there should be saved into the persistence volume as a result.

**Comment by sunkugupta** [comment]
I underst
