### ISSUE TITLE
Siebel auto scale

### ISSUE THREAD

**Issue by sunkugupta** [OracleSiebel/ConfiguringSiebel#113]
Hi Duncan

We are trying to dockerize siebel in AWS. We are planning to use AWS ECS as the orchestration tool. 

Will you be able to provide some ideas on how to autoscale siebel. At present, we are only able to handle preconfigured siebel scripts for containizing siebel. We would like to use AWS ECS provided auto scaling. However, there are challenges on how to provide siebel config data on the fly and also update the hostnames on all the servers. 

Thanks
Sunku

**Comment by OracleSiebel** [comment]
Hi Sunku,

I just noticed you closed this before I had a chance to comment.

The primary idea on autoscaling Siebel is to utilize HPA via Prometheus. The Siebel container will be instrumented to that it can respond to a URL request with the current level of activity of the various OMs supported by the profile running on the set. HPA configuration will determine when a given level of activity is reached and increase or decreases the pod count in response. When a new instance is started (scale up), the startup process might utilise a configured environment variable to determine if auto-deployment should happen, and if so, which profile should be deployed. Thus, in the startup of the container, a script can determine if the new node is known to gateway already (i.e. just start with the attached persistent volume) or not (i.e. deploy the configured profile on the current node via a REST call to SAI. Scale down is more challenging, as we mustn't lose user session data, and so in the case where HPA calls for the pod to be dropped, prestop can be configured to pause the SES instance and await a zero user count on the node before removal.

I can't comment on AWS ECS challenges around this, or how hostnames are configured automatically in that cloud as we don't intend to ever provide ready-to-go tooling that will plug and play with any cloud vendor. Rather we will solve the challenges as they pertain to OCI and customers taking up that tooling will have to adapt it for use on their target cloud. That said, the general strategy will remain the same and it'll probably come down to a few tweaks either in the initialisation scripts for the container (processing the provided hostname) and/or the YAML which configures the starting state of the container.

Hope this helps in some way.

Duncan
