### ISSUE TITLE
Siebel 21.10

### ISSUE THREAD

**Issue by sunkugupta** [OracleSiebel/ConfiguringSiebel#114]
Hey Duncan,

I am getting the below error for 21.10. The same scripts worked fine for 21.4. Please advice. 

 wget -r -q -np -nH --cut-dirs=2 -l 0 http://installers/siebel/21.10/Siebel_Enterprise_Server/
The command '/bin/sh -c mkdir -p -ma+rwx /siebel/ses /siebel/oraInventory  /stage && groupadd -g 487 siebel && useradd -m -g siebel -G siebel -u 9999 siebel && cd /mnt && date && echo Downloading installer && bash /config/getMDE.sh ${INSTALLSITE} ${VERSION}&& chmod a+rx /config && chown -R siebel:siebel /config && date && chmod +x /mnt/Siebel_Enterprise_Server/Disk1/install/unzip && chmod +x /mnt/Siebel_Enterprise_Server/Disk1/install/runInstaller && cd / && echo Installing Siebel ... && bash /config/mde_install.sh && rm -rf /mnt/Siebel_Enterprise_Server/ && echo Waiting for deployment of web archives ... && sleep 15 && chown -R siebel:siebel /siebel && chmod -R 755 /siebel/ses' returned a non-zero code: 8

**Comment by OracleSiebel** [comment]
Most likely reason is probably a change to the resp file.  Try running installer manually to get a current resp file and adjust that manually for the build.

**Comment by sunkugupta** [comment]
Yeah. I tried that and found only one variation ENVIRONMENT_TYPE="Production" which is present in the docker scripts and not in the 10.10 response file. I removed and still failed with same error.

Can you help me with troubleshooting steps?. I cant find much logs even in /var/lib/docker/containers/...

Thanks

**Comment by sunkugupta** [comment]
Nevermind. Silent install does not work with standalone AI. Looks like some bug with silent install. Will raise a ticket with support

**Comment by OracleSiebel** [comment]
Since 21.1 we've been building all tiers into one container and switching on containerMode. Suggest while you raise a ticket, you also raise a ticker to get access to the pre-built containers. Also from 21.4 they are now built with support for all languages (except for Web Tools), so it's possible the build we supply might be able to work for you. Definitely worth another look anyway.

**Comment by sunkugupta** [comment]
I am sorry. Silent install on standaone AI worked. I had a typo in my syntax. Looks like i am back to same problem using it with docker

Note: We are using lot of scripts and those get triggered through docker entry point. I might have to change my design a bit. I will take a look at the image and see if i can use it.

**Comment by OracleSiebel** [comment]
What do you mean by  'same problem' ?

**Comment by OracleSiebel** [comment]
If you need custom scripts triggered on entrypoint, you can still potentially use our build and add your scripting and modified entry point by adding a layer to our image. Just a thought.

**Comment by OracleSiebel** [comment]
We're diverging a little from original issue. Please close this if you've resolved the silent install issue, as that was the root cause.

**Comment by sunkugupta** [comment]
I still have the issue. I have attached logs for 21.4(Success) and 21.10(failure). 21.10 dowloads and at then end exits with code 8.

**Comment by OracleSiebel** [comment]
I'm going to take a wild guess that you ran out of disk space. The Siebel installer never runs. In the 21.4 install, The download of the Siebel installer starts on line 389 and completes on line 183,403:

389: Step 11/34 : RUN mkdir -p -ma+rwx /siebel/ses /siebel/oraInventory  /stage && groupadd -g 487 siebel && useradd -m -g siebel -G siebel -u 9999 siebel && cd /mnt && date && echo Downloading installer && bash /config/getMDE.sh ${INSTALLSITE} ${VERSION}

183,403: [0m[91mFINISHED --2021-11-21 11:30:53--
Total wall clock time: 2m 58s
Downloaded: 6753 files, 5.5G in 2m 33s (37.2 MB/s)

For 21.10, the installer start on 389 again:

Step 11/34 : RUN mkdir -p -ma+rwx /siebel/ses /siebel/oraInventory  /stage && groupadd -g 487 siebel && useradd -m -g siebel -G siebel -u 9999 siebel && cd /mnt && date && echo Downloading installer && bash /config/getMDE.sh ${INSTALLSITE} ${VERSION}

but finishes on line 293,717

[0m[91mFINISHED --2021-11-21 11:57:13--
Total wall clock time: 5m 6s
Downloaded: 7871 files, 10G in 4m 31s (38.8 MB/s)
[0mThe command '/bin/sh -c mkdir -p -ma+rwx /siebel/ses /siebel/oraInventory  /stage && groupadd -g 487 siebel && useradd -m -g siebel -G siebel -u 9999 siebel && cd /mnt && date && echo Downloading installer && bash /config/getMDE.sh ${INSTALLSITE} ${VERSION}' returned a non-zero code: 8

The installer never even starts in 21.10, but we see a lot of download activity.

Also interesting is that fact that for 21.4 you see 5.5GB downloaded, but this is almost double for 21.10.

Did you download more than you downloaded for 21.4? Bear in mind that getMDE is only downloading what you placed in the the install folder; it's not processed until the next step.

**Comment by sunkugupta** [comment]
In my previous post

21.4 -- I removed the ancestor repository files as they were irrelevant for us. Works fine with silent install and with docker
21.10 - I did not remove any ancestor repository files. Works fine with silent install and does not work with docker


Now i tested again with 21.10 . 

21.10 -  I removed the ancestor files and some other languages. Works fine with silent install and does not work with docker

In both 21.10 cases, the wget fails with error code 8. Yes, you are right, it fails before installing anything
I have attached the log files for this latest run.
[build.2021-11-22_07^%30.log](https://github.com/OracleSiebel/ConfiguringSiebel/files/7582442/build.2021-11-22_07.30.log)

**Comment by OracleSiebel** [comment]
My opinion remains unchanged. You are most likely running out of file space. This is impossible to see from the log file. Wget documentation suggest return value of 8 means a server issue:

https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html

Given the issue is during wget and not during install, you have to resolve this your end. Change disk space with 'watch df -h' during the attempt to install and make sure you are not running out of space. Double check the validity of the files you are installing, i.e. the location that the installer container is connected to. Is that install media fully valid?

**Comment by sunkugupta** [comment]
Yes. it is fully valid. Works fine with silent install

My host OS is ubuntu. Not sure if that matters.

**Comment by OracleSiebel** [comment]
I keep coming back to you being out of disk space until you confirm you are not. You need to run the installation again and watch disk space during install. To give you some idea why ...

You have the installation media on disk - 10GB
You will copy this into a temp container - another 10GB
You will then copy this into a final container - another 10GB

So you need a lot of working space to build your own container. You can observe disk space availability during installation with 'watch df -h'.

**Comment by sunkugupta** [comment]
I zipped the 21.10 installable and used wget to fetch the zipped file and plugged in unzip commands in the dockerfile. 

Issue is resolved after doing the above.

**Comment by OracleSiebel** [comment]
Glad that worked out. One reason against it is that it will increase further the disk space for the whole process. It's odd that we haven't seen this issue here, but thanks for reporting back anyway!
