### ISSUE TITLE
Kubernetes YAML files

### ISSUE THREAD

**Issue by fermatknsr** [OracleSiebel/ConfiguringSiebel#133]
Hi all,

We are trying to deploy the Containerized application to Kubernetes.

Could anyone provide a yaml file or an alternative approach to accelerate for deploying Siebel on Kubernetes?

Regars.

**Comment by duncanford** [comment]
Deployment on Kubernetes is beyond the scope of the content provided here, and not something we can quickly QA and release. I recommend you submit an SR on MOS to request access to Cloud Manager on OCI, which deploys the Siebel container to an OKE cluster on OCI. Once deployed, you should be able to review the YAML in that system.
