### ISSUE TITLE
Auto-Complete fix creating new issue

### ISSUE THREAD

**Issue by intu1991** [OracleSiebel/ConfiguringSiebel#21]
The custom code for completing the autocomplete works perfectly but after that when i step out of the field the focus is getting moved to the next applet and not the next field in the applet(We are loosing the focus).

Thanks,
Imtiyaz

**Comment by OracleSiebel** [comment]
Are you referring to the change for the auto-complete to accept matches starting-with instead of contains?

**Comment by OracleSiebel** [comment]
No response for over a month so closing issue. Suspect this was unrelated to the filter change.
