### ISSUE TITLE
DISA Error

### ISSUE THREAD

**Issue by 123ankita** [OracleSiebel/ConfiguringSiebel#23]
I am getting error when launching DISA. 
Error:- (SBL-UIJ-52894)"Failed to connect to DISA"
I used all the files which was provided in "UNIVERSALDISAHANDLER"
Help me to identify the issue, for which I am getting this error. It will be great help if u can find.

**Comment by OracleSiebel** [comment]
You probably need to open an SR via MOS. This is a place for providing examples, not support. That said, you might try comparing your code with that produced by the code generator here : http://duncanford.github.io/disa-code-generator/?prpm=undefined&object=DesktopForm&name=CunningPlugin&userprops=&comments=Yes&logging=No. Also, you didn't mention what version of Siebel and DISA you are using.

**Comment by 123ankita** [comment]
We are using Siebel :- IP16.0.0.0
DISA:- 2.17.2
Windows 7 , 64 bit
Browser:- Chrome:- 58/IE11/Firefox45.9.0

**Comment by OracleSiebel** [comment]
I see you're using Chrome 58 and DISA 2.17.2. This combination will fail as Chrome introduced new constraints on certificated. This is resolved in 2.17.4+, but you'll need to do a fresh install to replace your jks file. Have you made any progress?

**Comment by OracleSiebel** [comment]
No response, so assuming issue was fixed with a DISA re-install.
