### ISSUE TITLE
Integreation Siebel – GoogleMaps problem

### ISSUE THREAD

**Issue by igorvar** [OracleSiebel/ConfiguringSiebel#24]
Hi.
I liked your decision with a Google ( [https://github.com/OracleSiebel/ConfiguringSiebel/tree/master/ExampleCode/Open%20UI/Maps%20Integration/GoogleMaps](url)).  Unfortunately I can not find the file CCAppletList_No_Menu.swt. Can you help me with this?
Best regards,
Igor

**Comment by OracleSiebel** [comment]
Hi, I added the missing file into the asset list. Hope that helps.

https://github.com/OracleSiebel/ConfiguringSiebel/tree/master/ExampleCode/Open%20UI/Maps%20Integration/GoogleMaps/assets

**Comment by igorvar** [comment]
Hey.
Thanks for the quick response.
During the testing, I found the following problem in GoogleMapApiPR.js:
`if( typeof( SiebelAppFacade.GoogleMapApiPR ) === "undefined" ){

    SiebelJS.Namespace( "SiebelAppFacade.GoogleMapApiPR" );

	define ("siebel/custom/GoogleMapAPIPR", ["siebel/jqgridrenderer"], function () {
		 SiebelAppFacade.GoogleMapApiPR = ( function(){
`

this code not executed (begin from _define ("siebel/custom/GoogleMapAPIPR")_
I work on the dedicated client and the code is in C:\oracle\siebel\client\public\heb\SCRIPTS\siebel\custom

Best regards, 
Igor

**Comment by OracleSiebel** [comment]
The code was developed using the dedicated client and works for me. Note that the file should be registered in ManifestFiles as siebel/custom/GoogleMapAPIPR.js and also this must be the name (also case is important) of the file on the file system.

**Comment by igorvar** [comment]
You're right: 
> case is important

**Comment by OracleSiebel** [comment]
Working now?

**Comment by igorvar** [comment]
No. I have an error 

> This page did not load Google Maps correctly. See the JavaScript panel for technical details.
Could it be that the version markerclusterer.js does not work?

**Comment by igorvar** [comment]
Hey.
I solved the problem:
in script GoogleMapApiPR.js present this code:
`strHTML+='	  src="http://maps.googleapis.com/maps/api/js?sensor=true">'`
this is a problem.
I replaced it with:
`strHTML += '	  src="http://maps.googleapis.com/maps/api/js?&key=MY_API_KEY">';`
MY_API_KEY - this is the key that can be obtained here:
https://developers.google.com/maps/documentation/javascript/get-api-key
Thank you for your development and support.
Best regards,
Igor

**Comment by OracleSiebel** [comment]
Hi Igor,

I don't really understand why you need this change. For me the code works without this change. It's possible Google implement alternative rules based on the location from which the request comes. That said, I think your code is a useful addition for anyone wanting to use this in production who would ultimately be better off connecting to an API key. I'll add this detail into the code as commented code that other's can easily un-comment in order to user and make a reference to this in the readme. Thanks for your contribution !.

Regards,
Duncan

**Comment by igorvar** [comment]
sensor=true now not in use

**Comment by OracleSiebel** [comment]
in which case this should work (does for me):

strHTML+='	  src="http://maps.googleapis.com/maps/api/js">';
