### ISSUE TITLE
Git-Siebel integration

### ISSUE THREAD

**Issue by fatagun** [OracleSiebel/ConfiguringSiebel#28]
There are alot of questions about this and yet this is another one.

Is it possible to integration siebel with git?

If so how? Can you please elaborate?

Thanks.

**Comment by OracleSiebel** [comment]
Hi,

The only integration that I know of (at present) between Siebel and Github is the integration within SAM. Is this what you're thinking about? What specifically are you thinking of?

**Comment by OracleSiebel** [comment]
https://github.com/OracleSiebel/ConfiguringSiebel/tree/master/ExampleCode/SAM/REST/Services/Github

**Comment by fatagun** [comment]
I appreciate your prompt response. 

I started working for a very large telco, today. I am technical solution architect. One of the challanges they are having is versioning, tracking files, and deployment. 

Rather than github, I am interested in a in house git server. I believe srcctrl.bat can be modified for developers to checkin and checkout changes. Wanted to ask you if you can provide me a sample or already configured service/file for this purpose. 

Thanks again.

**Comment by OracleSiebel** [comment]
Essentially, your line of enquiry applies only to old versions of Siebel. Starting with IP17, srcctrl.bat integration is no longer an option as you no longer have a need for external source control. Siebel provides versioning directly within the repository.

Some resource to help you with discovery then:
Google directly against bookshelf:  https://cse.google.com/cse/publicurl?cx=003195936405786855498:9j8ulo6i7lw
A result after querying for srcctrl (with example file)
https://docs.oracle.com/cd/E74890_01/books/UsingTools/checking_in_and_out22.html
Detail regarding Workspaces: https://docs.oracle.com/cd/E88140_01/books/UsingTools/using_workspaces3.html#wp1014331

I can't find any example for scrctrl directly integrating with Github. You will probably need to experiment with it yourself to discover a solution.

**Comment by fatagun** [comment]
We are using Siebel 8.1. Does it have srcctl file?

**Comment by fatagun** [comment]
Also the reason I am interested in GIt is to enable branching on the project. ie: feature branches, defect branches, release, hotfix branches etc. Currently, there is a bit of a chaos for developers and release managers.

**Comment by OracleSiebel** [comment]
I highly recommend you contact your Oracle salesperson to arrange for some direct help. It sounds like you need some assistance from ACS.

Siebel 8.1 is the current version but could be patched to a large number of different Integration Packs (or IPs). All support srcctrl.bat until IP17. Your need for branching is exactly why we implemented that directly in the product. If you move to IP17 you will remove the need to deal with a local source control system, though you may find it still useful for artifacts not stored in the repository (i.e. custom PR/PM content, images, CSS)

**Comment by OracleSiebel** [comment]
Closing this issue as there is no specified issue with content here on this repository. This is more about a request to integrate with Github as a source control system. No updates or closure from the OP suggest the questions is answered. Please re-open if there is something new to add.
