### ISSUE TITLE
Margins and stuff

### ISSUE THREAD

**Issue by pranaykumarverma** [OracleSiebel/ConfiguringSiebel#29]
Added the below css code to get margins a showed in the #After screenshot. There may be still more places need to take care.

.fluid-form-group input {
    width: 80% !important;
	 margin-top: 2px;
    margin-bottom: 2px;
}

.fluid-form-group label {
    margin-top: 2px;
    margin-bottom: 2px;
}

.fluid-form-group .siebui-icon-dropdown {
	 margin-top: 2px;
   
}

.fluid-form-group .siebui-icon-datetime {
	 margin-top: 2px;
	
}

Need help on how to make this,

![image](https://user-images.githubusercontent.com/10824010/32474152-2943088e-c391-11e7-9f52-b35ff5d6981f.png)

A section below a section. Each sections creates a new column in the page i think.

Regards,
PV

**Comment by OracleSiebel** [comment]
Hi PV,

The idea of fluid flow is the you don't try to control exactly how the sections are laid out. The sections will re-flow according to the available screen real estate. From your screenshot, I get the feeling that you don't expect screen real estate to change for the users you have in mind. As such, I suggest two options. The first option is to simply alter which placeholder ids you are mapping based on the grid you have in mind. It looks like you want to divide the screen width in 3 (i.e. 4 columns per section), but have nothing in the third section. To set the columns from 3 to 4 per section, alter this part of the template:

`siebui-span-xl-3`

to

`siebui-span-xl-4`

In this way each section is now consuming a third of the screen width. Next, populate the 1000 and 1100 sections, leave the 1200 section empty, and then populate the 1300 and 1400 sections. This should give you a two sections, followed by a blank section, followed by two sections, and thus generate the layout you're looking for.
