### ISSUE TITLE
Siebel IP2013 checout project

### ISSUE THREAD

**Issue by fatagun** [OracleSiebel/ConfiguringSiebel#30]
Hello, 

I was able to integrate Siebel 2013 with on premise git server for a client. 

While checkin invokes srcctrl.bat file which is the script for integration. However, for checkout process this script is not being invoked. I put a echo and pause command right on the top of the script but the script doesn't run whatsoever. 

Is there a known defect about this? 

Thanks.

**Comment by OracleSiebel** [comment]
Hi,

I think the best thing is to go through [MOS](https://support.oracle.com)for this sort of question, as it's not related to content held here in Github.

Thanks.
