### ISSUE TITLE
Unable to view list applet after registering PM PR for form applet against it.

### ISSUE THREAD

**Issue by itzketki** [OracleSiebel/ConfiguringSiebel#40]
Hi,

We are trying to make a control read only based on another one in Siebel Open UI form applet. The form applet opens in edit mode when New button on List Applet is clicked.
I have created JS files which are based on Physical Renderer. But the list applet is not visible now.
Kindly suggest some resolution.

Thanks,
Ketki

**Comment by itzketki** [comment]
@duncanford please help me on this issue.

**Comment by OracleSiebel** [comment]
Is this an issue with some of the content here on Github?

**Comment by OracleSiebel** [comment]
Did you use the code generator?

https://duncanford.github.io/prpm-code-generator/?prpm=PR&object=DesktopForm&name=BeautifulThing&userprops=&comments=Yes&logging=No

**Comment by OracleSiebel** [comment]
Closing this due to no further response.
