### ISSUE TITLE
SAI dockerfile chmod

### ISSUE THREAD

**Issue by john612** [OracleSiebel/ConfiguringSiebel#42]
I tried to run the SAI docker file through the build-all script and it did a chmod on several of the directories including the ssh directory i was then kicked out of the server and the unix admin told me it was hosed due to the chmod on the directories. please let me know why it is trying to do a chomd on some of the kernel directories?

**Comment by OracleSiebel** [comment]
I assume you're referring to this line John?

https://github.com/OracleSiebel/ConfiguringSiebel/blob/master/Containerization/Docker/ol7/build/base_siebel/build/build-all#L14

Now I think back on it, I'm not a fan of the way I did this, and it was probably overkill just to make sure of the necessary access to the installer files. I don't know what you mean by kernel directories though? This might be a feature of where you've set the whole thing up. Ideally you would have git cloned this repository, and this chmod is assumed to be run from the folder in which it sits, meaning that '..' will refer to the folder above the build all. If you run the build from elsewhere though, then .. could refer elsewhere and this could be what you're encountering. Certainly comment it out in the first instance, or execute it once manually on the folder above the build all script.

**Comment by john612** [comment]
please close
