### ISSUE TITLE
Docker images small

### ISSUE THREAD

**Issue by john612** [OracleSiebel/ConfiguringSiebel#45]
I have run the build-all for the enterprise and i run docker images command after it says completed successfully and I get
 docker images
REPOSITORY                                                    TAG                 IMAGE ID            CREATED              SIZE
registry.local.com:5000/siebel/ses                            17.0                d7669bbee552        10 seconds ago       656MB
registry.local.com:5000/siebel/cgw                            17.0                826c99426c81        About a minute ago   656MB
registry.local.com:5000/siebel/sai                            17.0                4f625d374563        About a minute ago   656MB
registry.local.com:5000/oracle/database-instantclient/32bit   12.2.0.1            eaf71381bff5        21 hours ago         656MB
oraclelinux                                                   latest              bf3369f67ef1        2 weeks ago          234MB
 However there is nothing in the containers directories beyond ses and sai. 
drwxrwxrwx 2 root root 4096 Oct 15 19:19 oraInventory
drwxr-xr-x 2 root root 4096 Oct 16 16:42 sai
drwxrwxrwx 2 root root 4096 Oct 15 19:19 ses
[root@0df4de5a1b6b siebel]# cd ses
[root@0df4de5a1b6b ses]# ll
total 0
[root@0df4de5a1b6b ses]# cd ../sai
[root@0df4de5a1b6b sai]# ll
total 0
It looks like nothing was installed.

**Comment by john612** [comment]
It also did not call the SMC script I have in the build folder

**Comment by OracleSiebel** [comment]
It looks very much like each of the installers failed to access, or find, the actual Siebel installers. Where did you place the Siebel installation folders?

**Comment by john612** [comment]
drwxr-xr-x 2 siebel siebel 4096 Oct 15 14:06 build
-rwxr-xr-x 1 siebel siebel   46 Oct 14 17:22 build.log
drwxr-xr-x 2 siebel siebel 4096 Oct 12 16:52 cgw
-rwxr-xr-x 1 siebel siebel 3729 Oct 12 16:52 readme.md
drwxr-xr-x 2 siebel siebel 4096 Oct 14 11:31 sai
drwxr-xr-x 2 siebel siebel 4096 Oct 12 16:52 ses
drwxr-xr-x 3 siebel siebel 4096 Oct 12 17:15 Siebel_Enterprise_Server
-rwxr-xr-x 1 siebel siebel 3544 Oct 11 13:42 siebelkeystore.jks




Thank you,

John Murphy
 

    On Tuesday, October 16, 2018, 4:38:42 PM CDT, OracleSiebel <notifications@github.com> wrote:  
 
 
It looks very much like each of the installers failed to access, or find, the actual Siebel installers. Where did you place the Siebel installation folders?

**Comment by OracleSiebel** [comment]
Closing this as I worked with John directly to move things forward. Feel free to re-open a new issue if you're still stuck.
