### ISSUE TITLE
Installer fails with the following error on all images

### ISSUE THREAD

**Issue by wildtangent** [OracleSiebel/ConfiguringSiebel#46]
When running build-all the installers on all 3 images fail with the following error

```
Loading products list. Please wait.
SEVERE:Values for the following variables could not be obtained from the command line or response file(s): 
  ToplevelComp(TopLevelComp) 
Silent install cannot continue.
```
Please can you advise what the correct TopLevelComp value should be?

Command executed:
```
./build-all 17.0 my-repo siebel my-repo/database-instantclient-32bit:12.2.0.1 2>&1 | tee build.log
```

**Comment by OracleSiebel** [comment]
This is possibly just a problem with read-write access to the installation media from the perspective of the user running the build-all script? You shouldn't ever need to set TopLevelComp if I didn't provide a value for that, as I'm able to build with the content supplied.

**Comment by OracleSiebel** [comment]
Hi. Thanks for clarifying your attempted install version. In fact, we never attempted to install 15 or 16 in this way, and don't have time to investigate potential installation issues that occur with older version. I'll update the instructions to make this clearer.

Regarding the parameters, you may find it easier, and it may solve other potential install issues, to roll back a little further. Perform a standard install, save the response file, and then use that response file as part of your attempt to install IP15.

Part of the issue with any attempt with IP15 will be that Siebel will be less self-contained. IP17 introduces the SAI layer, which replaces the need for a third party web server.

If you are successful with an IP15 install, it would definitely be useful to try to contain this information here to help others. I thought I had earlier read, through searching on Google, of someone else working through that, but I cannot find that article now. Let's see how much change is involved, at which point we can decide how best to incorporate such content.

**Comment by OracleSiebel** [comment]
I managed to dig up an installer response file for IP15. You might try adapting this if you haven't already produced your own:

RESPONSEFILE_VERSION=2.2.1.0.0
s_shiphomeLocation="/net/slc/export/engfs02/8.2/patch/15.0SIA[23048]/Release/Linux/Server/Siebel_Enterprise_Server/Disk1"
FROM_LOCATION="/net/slc/export/engfs02/8.2/patch/15.0SIA[23048]/Release/Linux/Server/Siebel_Enterprise_Server/Disk1/stage/products.xml"
s_topLevelComp="oracle.siebel.ses"
s_SiebelVersion="15.0.0"
ORACLE_HOME="/export/home/sblqa1/23048/ses"
ORACLE_HOME_NAME="BIT_SES_23048"
selectedLangs="[English]"
DEINSTALL_LIST={"oracle.siebel.ses","15.0.0"}
SHOW_DEINSTALL_CONFIRMATION=true
SHOW_DEINSTALL_PROGRESS=true
txt_email=""
txt_pass=""
s_installType="New Installation"
s_txt_programFolder="Siebel Enterprise Server 15.0.0"
b_isGatewayInstalled="true"
b_isSiebsrvrInstalled="true"
b_isDBInstalled="false"
b_isEAIInstalled="false"
b_isLDAPInstalled="false"
b_isLDAPInstalled="true"

**Comment by OracleSiebel** [comment]
Closing this as it pertains to an earlier version of Siebel than IP17, against which this content was never tested.
