### ISSUE TITLE
Siebel Image build giving error su: System error

### ISSUE THREAD

**Issue by spadwale** [OracleSiebel/ConfiguringSiebel#53]
Hi,

When  I am trying to create Siebel base version images, it is failing with error as "su: System error". Hence the empty images are created for all three entities. I checked running the images there is no siebel user created in those. Also if I create the user manually using the commands from dockerfile, although the user gets created without any error when I try to run command "su siebel" i get the same error.

Thanks,

**Comment by OracleSiebel** [comment]
The suggested command to build generates a log file - can you post that here please.

**Comment by spadwale** [comment]
Hi,

PF log file contents

Beginning build for 17.0np
Tue Mar 12 15:05:16 IST 2019
...
Building sai element for 17.0np
...
Sending build context to Docker daemon  2.213GB^M^M
Step 1/10 : ARG DBCONTAINER=registry.local.com:5000/oracle/database-instantclient/32bit:12.2.0.1
Step 2/10 : FROM  oraclelinux:latest
 ---> 968ea3e71bea
Step 3/10 : COPY sai/oraInst.loc sai/sai.rsp sai/setup.sh siebelkeystore.jks /config/
 ---> Using cache
 ---> 34b99418068d
Step 4/10 : COPY Siebel_Enterprise_Server /mnt/Siebel_Enterprise_Server/
 ---> Using cache
 ---> 23df7d2c33ce
Step 5/10 : ENV http_proxy="http://XXX:CCCC@ppp.XXX.com:80"
 ---> Running in 151ce22a5f7a
Removing intermediate container 151ce22a5f7a
 ---> a3401feb0eac
Step 6/10 : ENV https_proxy="https://XXX:CCCC@ppp.XXX.com:80"
 ---> Running in c5c3acfd9be2
Removing intermediate container c5c3acfd9be2
 ---> 58b76d26ee76
Step 7/10 : ENV no_proxy=172.*
 ---> Running in ff2d638c47ef
Removing intermediate container ff2d638c47ef
 ---> 5d8c9274b6cd
Step 8/10 : RUN mkdir -p -ma+rwx /siebel/sai /siebel/oraInventory  /stage && groupadd -g  487 siebel && useradd -m -g siebel -G siebel -u 9999  siebel && yum -y install  tcsh  ksh && yum clean all && rm -rf /var/cache/yum/x86_64  && rm -rf /var/cache/yum/i686 && echo Installing Siebel ... && bash /config/setup.sh && rm -rf /mnt/Siebel_Enterprise_Server/ && echo Waiting for deployment of web archive ... && sleep 30 && chmod -R 755 /siebel/sai
 ---> Running in 45a233f2f896
Loaded plugins: ovl, ulninfo
Resolving Dependencies
--> Running transaction check
---> Package ksh.x86_64 0:20120801-139.0.1.el7 will be installed
---> Package tcsh.x86_64 0:6.18.01-15.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved
================================================================================
 Package     Arch          Version                      Repository         Size
================================================================================
Installing:
 ksh         x86_64        20120801-139.0.1.el7         ol7_latest        883 k
 tcsh        x86_64        6.18.01-15.el7               ol7_latest        338 k

Transaction Summary
================================================================================
Install  2 Packages

Total download size: 1.2 M
Installed size: 3.8 M
Downloading packages:
--------------------------------------------------------------------------------
Total                                              191 kB/s | 1.2 MB  00:06
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : tcsh-6.18.01-15.el7.x86_64                                   1/2
  Installing : ksh-20120801-139.0.1.el7.x86_64                              2/2
failed to link /usr/share/man/man1/ksh.1.gz -> /etc/alternatives/ksh-man: No such file or directory
  Verifying  : ksh-20120801-139.0.1.el7.x86_64                              1/2
  Verifying  : tcsh-6.18.01-15.el7.x86_64                                   2/2

Installed:
  ksh.x86_64 0:20120801-139.0.1.el7         tcsh.x86_64 0:6.18.01-15.el7

Complete!
Loaded plugins: ovl, ulninfo
Cleaning repos: ol7_UEKR5 ol7_latest
Installing Siebel ...
^[[91msu: System error
^[[0mThe command '/bin/sh -c mkdir -p -ma+rwx /siebel/sai /siebel/oraInventory  /stage && groupadd -g  487 siebel && useradd -m -g siebel -G siebel -u 9999  siebel && yum -y install  tcsh  ksh && yum clean all && rm -rf /var/cache/yum/x86_64  && rm -rf /var/cache/yum/i686 && echo Installing Siebel ... && bash /config/setup.sh && rm -rf /mnt/Siebel_Enterprise_Server/ && echo Waiting for deployment of web archive ... && sleep 30 && chmod -R 755 /siebel/sai' returned a non-zero code: 1
Deleted Images:
deleted: sha256:2771a146ed58067dcfb01e715d3e6568a90ebbffbae322ff70cfa1c48d2f2a56
deleted: sha256:9747f146a9e854d14ab4c962b51824d0e43ccb617a91703bec848856d6f5900f
deleted: sha256:a2d88b9139fcf72216dd5cf317f884fe49accb4b7145969be55ea5825e48c85d
deleted: sha256:2dcc0f8da1043a3956c9cac0f8ddb7cc319e7774547e443843b6a3012431e997
deleted: sha256:f76583253c95be6fbb16cf2a79a9766f1df88f7daa13a60246b54ed3f27dc6f1
deleted: sha256:0b893af92543dcd3df6f844d8dec11c3a1830308d6186741b07516fba453a111
deleted: sha256:af767eaedadf0bf8f8c46e5d38d39a3d39cd455a4294574f6c5b9009da69848e
deleted: sha256:1dbeaec7ab206f8ebb4403fbd31c9f79b6a4934390f386e63a34af8be15167ff
deleted: sha256:28c8b341d414e017341683bd022d511ef0e48f890a248e5ee6403847f371adac
deleted: sha256:d7ed7ee5f12674541ac8ab08d950962e52e3b729d15bb210572f2767746fa72b
deleted: sha256:2576056c8ea99b47dceee714d72fb42588fa3d5fd3bb51228e8005254a8dba92

Total reclaimed space: 528.6MB

**Comment by OracleSiebel** [comment]
This seems to be some security issue on your OS. I've only tested this on OEL 7.6 as shown in the video so I can't be sure about other OSes. What are you using? Can you give the output of

uname -a

**Comment by spadwale** [comment]
output of uname -a on host 

Linux localhost.localdomain 4.1.12-112.16.4.el7uek.x86_64 #2 SMP Mon Mar 12 23:57:12 PDT 2018 x86_64 x86_64 x

**Comment by OracleSiebel** [comment]
Lets try to simply this and remove as many variables as possible. If I understand you so far, the following simple test will still result in an issue for you.

Create a new folder and in it create a dockerfile with the following:

FROM oraclelinux:latest
RUN groupadd -g 487 banana && useradd -m -g banana -G banana -u 9999 banana

Build this with

docker build -t testsu .

Now test this with

docker run -it testsu bash

Next

su banana

Does this test also produce a failure with su?

**Comment by spadwale** [comment]
I followed these steps and the result was same. 
[root@84eb073dc8d3 /]# su banana
su: System error


So I went ahead and tried creating user and su by running the original oraclelinux image I had used and got the same error.  Now this image was NOT pulled on this machine as it is behind corporate firewall.
I had pulled image on another Windows laptop using open internet.  I used docker toolbox to pull the image on this laptop.  Then I used command "docker save oraclelinux > oraclelinux.tar" to save the image to tar file. I copied this file to my OL7 machine and used command "docker load < /media/sf_shared/dock/oraclelinux.tar".
If I use the steps given on oraclelinux image on my Windows laptop it works fine, so I think the image got corrupted somewhere in transfer.  Is there a better way to transfer the image from Windows laptop to OL7 server?
Also I had to use Windows laptop because I was not able to provide authentication details for corporate proxy while using docker pull command, is there a way to use this command with proxy authentication?

Thanks,

**Comment by OracleSiebel** [comment]
Does this help

https://docs.docker.com/network/proxy/

**Comment by spadwale** [comment]
This document does not give information about how to provide user/pass for proxy authentication.  I tried using the usual format for Linux http_proxy env variable, but it fails to detect user:pass in the value.

Also I wanted to know, having this image and steps from Oracle means that Oracle is now supporting Siebel on Docker?

**Comment by OracleSiebel** [comment]
Oracle provides no official support for Siebel on Docker at present. You should see this repository as a guide providing one way in which you might try to install Siebel using Docker. Should you choose to run Siebel on Docker and run into issues, you might reasonably expect Oracle to request you prove that the issue is not Docker-related by first replicating your issue in a standard install. This repository aims simply to help customers get started on a journey that many are already taking.

Your challenges at present seem largely related to unfamiliarity with Docker. I've queried Google for you again with this query:

docker proxy user password

The suggestion I found was that you can try the following for usernames and passwords with proxies

export HTTPS_PROXY=https://username:password@192.168.33.10:3128/

I guess you can use a similar format with the config.json file.

**Comment by spadwale** [comment]
Hi,

I was able to resolve the su error by using pre-built docker VM from Oracle.  

Thanks,

**Comment by OracleSiebel** [comment]
Thanks for the update. Could you add a link to the pre-built VM you used to help anyone else with the same issues please?

**Comment by spadwale** [comment]
I used VM from link https://www.oracle.com/technetwork/server-storage/linux/downloads/vm-for-hol-1896500.html
