### ISSUE TITLE
component logs not visible in log folder

### ISSUE THREAD

**Issue by PeterP55P** [OracleSiebel/ConfiguringSiebel#54]
I have an issue with finding component logs. I'm not sure if I did something wrong during the installation/configuration but I didn't receive any error. The problem is that even when I increase log level to 5 on AOM (e.g. callcenter) no logs are generated in log folder. Can you please advice what can be wrong or if you are having the same issue?

**Comment by OracleSiebel** [comment]
Hi. Given that you find yourself able to increase the log levels it seems reasonable to assume that everything is working. The log files will be in the volume you've assigned for persistent storage. e.g. /persistent/siebsrvr/enterprises/ENT/SES/log. What sort of error are you getting?

**Comment by PeterP55P** [comment]
Thanks I somehow overseen this setup. In my case logs are presented in /persistent/siebsrvr/enterprises/ENT1/SES1/log (I'm running multi-server configuration). I can see AOM's logs there.

**Comment by OracleSiebel** [comment]
Thanks for confirming and closing. Out of interest, where were you actually looking? Inside the container, the same location should be linked to persistent storage in, e.g. /siebel/ses/siebsrvr/enterprises....

**Comment by PeterP55P** [comment]
the path I provided is from inside of the container. Originally I was expecting log in standard location <SIEBEL_HOME>/log. Anyway, outside of the container it looks as follows /app/docker_volumes/ENT1/SES1/siebsrvr/enterprises/ENT1/SES1/log where "/persistent" is bind to "/app/docker_volumes/ENT1/SES1" and the first part of the path is my general folder for Docker's persistent volumes.

**Comment by OracleSiebel** [comment]
Thanks for the detail. I had a hunch you might be checking the place you would expect to find them for a Windows install.
