### ISSUE TITLE
Oracle client installation error OL 7.5

### ISSUE THREAD

**Issue by spolepally** [OracleSiebel/ConfiguringSiebel#56]
I am unable to install oracle client with the new docker file in OL 7.5 . Its failing at step 4/5 , please see attached log 
[build.2019-03-24_03%3A56.log](https://github.com/OracleSiebel/ConfiguringSiebel/files/3004023/build.2019-03-24_03.3A56.log)

**Comment by duncanford** [comment]
It seems that that latest version of oraclelinux already has a multiversion install of libstdc++, so you'l need to remove that library from the yum install for this and also the base installs.

**Comment by spolepally** [comment]
Thanks it worked after removing libstdc++ library from oracle client dockerfile. I removed  libgcc library from cgw and ses dockerfile for base images.

**Comment by OracleSiebel** [comment]
Thanks for confirming. Closing the issue.
