### ISSUE TITLE
Unable to start Siebel server service

### ISSUE THREAD

**Issue by spadwale** [OracleSiebel/ConfiguringSiebel#58]
Hi,

When I start containers using "bash startAll 19.01 ent1.sh" command SAI and CGW containers and services start fine. I can also connect to SMC and see configuration. However SES container is not starting properly. I can see siebel service started for few mins and then it disappears from host. It also hangs all SSH sessions on my host. I could not find any error in containerInit.log log file and there are no log files created in Siebel except SiebSrvr.log.  This file has below errors
GenericLog	GenericError	1	000000025cc00101:0	2019-04-24 13:16:15	(sccnmsys.cpp (1306) err=2883609 sys=0) SBL-SCC-00025: No value found in the Gateway. Default value in the repository is used.
GenericLog	GenericError	1	000000025cc00101:0	2019-04-24 13:16:15	(sccitems.cpp (310) err=2555932 sys=0) SBL-SCM-00028: Key not found
GenericLog	GenericError	1	000000025cc00101:0	2019-04-24 13:16:15	(sccconfg.cpp (2155) err=2555932 sys=0) SBL-SCM-00028: Key not found
SisnTcpIp	SisnSockError	1	000000025cc00101:0	2019-04-24 13:16:15	1444749504: [SISNAPI TLS] failed to read PARAM_GENERIC_ENABLE_OPENSSL parameter
SisnTcpIp	SisnSockError	1	000000025cc00101:0	2019-04-24 13:16:15	1444749504: [SISNAPI TLS] failed to read PARAM_GENERIC_ENABLE_OPENSSL parameter

Am I using correct way to start containers? if yes, what is the issue?

Thanks,

**Comment by OracleSiebel** [comment]
How can the SES container hang SSH sessions on your host? They're completely unrelated processes.
The launch command is correct and this is how I start the system. The issue is impossible to locate from the information supplied. Issues with TLS tend to point to an issue with the keystore. How did you generate that? What is the content of your ent1.sh?

**Comment by spadwale** [comment]
It seems impossible, but its happening. After SES container is started, and siebsvc process for Siebel server 
fails, I can't run any command in any SSH sessions. If new sessions is started I never get a prompt.
Kestore was generated using command
bash keygen -r .. -s siebel -d *.company.com -c my-custom-ca 2>&1 | tee keygen.log

Below are the contents of my ent1.sh

ROOT=/home/holuser/ConfiguringSiebel-master/Containerization/Docker/ol7/manage/scripts/automate-architecture
PV=/var/lib/docker/volumes/PV
CONTAINERBASE=registry.local.com:5000/siebel
DOMAIN=company.com
ENTERPRISE1=ENT1
DBHOST=XXX.17.XX.XXX
DBPORT=1521
DBINST=XXX.XXX.XXX.com
TNSCONN=siebdb17
DOCKERNET=siebelnet
TBLO=SIEBEL
PORT=443
USER=SADMIN
PASSWD=XXXXXXXXXX
GWUSER=SADMIN
GWPASSWD=XXXXXXXXXXX
ANONUSER=GUESTCST
ANONPASS=XXXXXXXX
RUNASUSER=9999
ENTPROFILE=ENT
HWSERVER=localhost
COMPGRPS=callcenter,siebelwebtools,eai
SES1SERVERNAME=SES

readonly compsToManual=(
	'BusIntBatchMgr'
	'CustomAppObjMgr_enu'
	'SServiceObjMgr_enu'
	'eServiceObjMgr_enu'
	'JMSReceiver'
	'InfraEAIOutbound'
	'SMQReceiver'
	'MSMQRcvr'
	'MqSeriesSrvRcvr'
	'MqSeriesAMIRcvr'
	'JMSReceiver'
	'EIM'
	'CustomAppObjMgr_enu'
	'BusIntMgr'
	'BusIntBatchMgr'
)

**Comment by OracleSiebel** [comment]
On the face of it, the setup looks OK. I created a video which is linked at the bottom of the main page:

https://github.com/OracleSiebel/ConfiguringSiebel/tree/master/Containerization/Docker

Can you describe all the ways in which your setup differs from that shown in the video?

**Comment by spadwale** [comment]
Below steps were done differently than the video

Oracle Linux 7.4 pre-built VM for docker labs used.
oraclelinux image was pulled on the laptop then exported , transferred to server and then imported into docker running on VM.
Although I have used tag 19.01 for images, I am actually using patch set 18.10 for building images

**Comment by spadwale** [comment]
Also there are multiple errors like these in SES config*.log

FINER: 
Exited with error 5004
Apr 26, 2019 6:05:53 AM oracle.siebel.configurator.utility.ConfigUtility runProgram
INFO: Config Util Exit Value: 1

**Comment by OracleSiebel** [comment]
I'm really sorry that I can't support you more. This is not an official product at this stage, so SRs won't help you either. I can only recommend that you do follow the exact process I outlined in the video as that is known to work. Whatever is going wrong for you is a result of the differences. If you have a working version, you might be able to see why you're chosen path fails and work forward from there.
