### ISSUE TITLE
Java Nullpointer exception on update process for all images

### ISSUE THREAD

**Issue by osnsergey** [OracleSiebel/ConfiguringSiebel#59]
I am getting the following error when trying to build updated versions of the containers:

Starting Oracle Universal Installer...

Preparing to launch Oracle Universal Installer from /tmp/OraInstall2019-06-14_12-44-20PM. Please wait ...

===================================================

***************Error***************

Press Any Key..................
java.lang.NullPointerException
        at com.oracle.siebel.apiinstaller.InstallerUtility.loadResponseFile(InstallerUtility.java:541)
        at oracle.sysman.oio.oioc.OiocOneClickInstaller.main(OiocOneClickInstaller.java:303)

I'm updating from Siebel IP17 to 19.5.0.0.

; This file is used to keep track of the products in this image.
; Do not modify this file.
[19.5.0.0.update]
Linux=Siebel_Enterprise_Server

**Comment by osnsergey** [comment]
Hi, it seems it depends on OS configuration, etc. On another machine it passes without that error. Thanks.

**Comment by OracleSiebel** [comment]
Thanks for the report and the confirmation.
