### ISSUE TITLE
The user ID or password that you entered is incorrect.

### ISSUE THREAD

**Issue by osnsergey** [OracleSiebel/ConfiguringSiebel#60]
Login attempt with SADMIN on SCM after first launch of persistent version of containers fails with error: "The user ID or password that you entered is incorrect."

**Comment by OracleSiebel** [comment]
You need to supply exactly whatever you configured:

https://github.com/OracleSiebel/ConfiguringSiebel/blob/master/Containerization/Docker/ol7/build/base_siebel/sai/sai.rsp#L31
https://github.com/OracleSiebel/ConfiguringSiebel/blob/master/Containerization/Docker/ol7/build/base_siebel/sai/sai.rsp#L36

**Comment by osnsergey** [comment]
Ok, so that user and user in the Siebel DB could have different passwords or they should be the same?

**Comment by OracleSiebel** [comment]
That user is just the initial setup password to gain access to the management console. For more information please consult the relevant guide in Siebel Bookshelf - e.g. https://docs.oracle.com/cd/E88140_01/books/SiebInstWIN/SiebInstCOM_ConfigSES4.html#wp4844821

**Comment by osnsergey** [comment]
Understood, thanks.
