### ISSUE TITLE
Errors after "bash stopAll ent1.sh" - siebenv.sh: No such file or directory

### ISSUE THREAD

**Issue by osnsergey** [OracleSiebel/ConfiguringSiebel#62]
bash stopAll ent1.sh

Thu Jun 20 11:15:14 PDT 2019
bash: /siebel/ses/siebsrvr/siebenv.sh: No such file or directory
bash: stop_server: command not found
bash: /siebel/cgw/gtwysrvr/siebenv.sh: No such file or directory
bash: stop_ns: command not found

**Comment by OracleSiebel** [comment]
These errors are benign. They're the result of not having been able to fully start the service. The next version of the build will not show such errors.
