### ISSUE TITLE
build-all-base error su: System error

### ISSUE THREAD

**Issue by osnsergey** [OracleSiebel/ConfiguringSiebel#63]
The step build-all-base fails with error su: System error

OS: Oracle Enterprise Linux 7.6

uname -a
Linux 4.1.12-124.28.5.el7uek.x86_64 #2 SMP Thu Jun 20 12:00:04 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by OracleSiebel** [comment]
try sudo su before executing build-all-base

**Comment by osnsergey** [comment]
I'm logged in as root

**Comment by OracleSiebel** [comment]
Sorry - this early build system isn't as well instrumented as the current version.
Is this the only output you get? I assume it's failing at the point that an installer attempts to run the su command in one of the dockerfile definitions. Can you not detect the difference in your setup from mine by watching this step on the video? https://www.youtube.com/watch?v=MvETSsryqok&t=2536s

**Comment by osnsergey** [comment]
The difference is only I use root user

**Comment by osnsergey** [comment]
Tried another user + sudo su. Got the same system error...

**Comment by OracleSiebel** [comment]
Have you turned off selinux?

**Comment by osnsergey** [comment]
Hm, it helped, though in your video it was done after you started build-all-base ) Thanks!

**Comment by OracleSiebel** [comment]
Thanks for confirming you got through.
