### ISSUE TITLE
SES doesn't start

### ISSUE THREAD

**Issue by osnsergey** [OracleSiebel/ConfiguringSiebel#64]
I finally went much further and was able to use "manage" utils to start containers and configure them.
SMC console shows all components are 'green' as in your video but app/callcenter/enu shows server is not started.
I've checked the logs in **/var/lib/docker/volumes/PV/ENT1/SES/cfgtoollogs/cfg** and found a lot of errors:

Calling typeUtil.buildNSCmd...
argument: $Gateway.UseDefault
dataType: 
type: NSAttrib
Command after calling typeUtility.buildNSCmd: /siebel/ses/siebsrvr/bin/srvredit -g cgw-ENT1:4330  **-e notempty** -u SADMIN -p ******* -a  -c \$Gateway.UseDefault
Running above command using configUtil.runProgram
Jul 03, 2019 9:56:33 PM oracle.siebel.configurator.utility.ConfigUtility runProgram
FINER: Run Program
Jul 03, 2019 9:56:33 PM oracle.siebel.configurator.utility.ConfigUtility runProgram
FINER: configUtil runProgram Executing Command: /bin/sh -c /siebel/ses/siebsrvr/bin/srvredit -g cgw-ENT1:4330  **-e notempty** -u SADMIN -p ******* -a  -c \$Gateway.UseDefault
Jul 03, 2019 9:56:33 PM oracle.siebel.configurator.utility.ConfigUtility runProgram
FINER: 
Exited with error 5004
**Jul 03, 2019 9:56:33 PM oracle.siebel.configurator.utility.ConfigUtility runProgram
INFO: Config Util Exit Value: 1**
Jul 03, 2019 9:56:33 PM oracle.siebel.configurator.utility.ConfigUtility runProgram
FINER: ConfigUtil RunProgram output: Exited with error 5004

=====Condition check NSATTRIB Not Masked and Not ReadOnly=====
Calling typeUtil.buildNSCmd...
argument: $Server.Last
dataType: 
type: NSAttrib
Command after calling typeUtility.buildNSCmd: /siebel/ses/siebsrvr/bin/srvredit -g cgw-ENT1:4330  -e ENT1 -s SES -u SADMIN -p ******* -a  -c \$Server.Last
Running above command using configUtil.runProgram
Jul 03, 2019 9:56:33 PM oracle.siebel.configurator.utility.ConfigUtility runProgram
FINER: Run Program
Jul 03, 2019 9:56:33 PM oracle.siebel.configurator.utility.ConfigUtility runProgram
FINER: configUtil runProgram Executing Command: /bin/sh -c /siebel/ses/siebsrvr/bin/srvredit -g cgw-ENT1:4330  -e ENT1 -s SES -u SADMIN -p ******* -a  -c \$Server.Last
Jul 03, 2019 9:56:33 PM oracle.siebel.configurator.utility.ConfigUtility runProgram
FINER: 
Exited with error 5004
**Jul 03, 2019 9:56:33 PM oracle.siebel.configurator.utility.ConfigUtility runProgram
INFO: Config Util Exit Value: 1**

Recursively Run Program # 0
Recursively Run Program command: /siebel/ses/siebsrvr/bin/srvrcfg -u SADMIN -p ******* -g cgw-ENT1:4330 -e ENT1 -a components -i /siebel/ses/siebsrvr/bin/enu/omdefs.run -c ALL
Jul 03, 2019 9:56:46 PM oracle.siebel.configurator.utility.ConfigUtility runProgram
FINER: Run Program
Jul 03, 2019 9:56:46 PM oracle.siebel.configurator.utility.ConfigUtility runProgram
FINER: configUtil runProgram Executing Command: /bin/sh -c srvrcfg -u SADMIN -p ******* -g cgw-ENT1:4330 -e ENT1 -a components -i /siebel/ses/siebsrvr/bin/$$DeployedLanguage$$/omdefs.run -c ALL
Jul 03, 2019 9:56:58 PM oracle.siebel.configurator.utility.ConfigUtility runProgram
FINER: 
**Error creating Parameter:AllowAnonUsers		 for Comp:SMObjMgr_enu in CompGroup:MktgOM
Strict Flag set to FALSE, continuing with the next Object...**

**Error creating Parameter:EnableSIDataLossWarning for Comp:SMObjMgr_enu in CompGroup:MktgOM
Strict Flag set to FALSE, continuing with the next Object...**

**Error creating Parameter:EnableSIFocusTracking for Comp:SMObjMgr_enu in CompGroup:MktgOM
Strict Flag set to FALSE, continuing with the next Object...**

**Error creating Parameter:HighInteractivity for Comp:SMObjMgr_enu in CompGroup:MktgOM
Strict Flag set to FALSE, continuing with the next Object...**

**Error creating Parameter:ListRowStyle for Comp:SMObjMgr_enu in CompGroup:MktgOM
Strict Flag set to FALSE, continuing with the next Object...**

**Error creating Parameter:UserAgentFile for Comp:SMObjMgr_enu in CompGroup:MktgOM
Strict Flag set to FALSE, continuing with the next Object...**

**Error creating Parameter:AllowAnonUsers		 for Comp:eMarketObjMgr_enu in CompGroup:MktgOM**

**Comment by osnsergey** [comment]
SiebSrvr.log has many errors:

1021 2019-07-03 22:45:15 2019-07-03 22:45:41 +0000 000000ac 001 ffff 0001 09 SiebSrvr 263 1444185728 /siebel/ses/siebsrvr/log/SiebSrvr.log 19.5.0.0 [23073] ENU
SisnTcpIp	SisnSockError	1	000000025d1d0107:0	2019-07-03 22:45:15	1444185728: [SISNAPI TLS] failed to read PARAM_GENERIC_ENABLE_OPENSSL parameter
GenericLog	GenericError	1	000000025d1d0107:0	2019-07-03 22:45:15	($Header: (1191) err=1181216 sys=0) SBL-NET-01568: Failed to read configuration parameter
GenericLog	GenericError	1	000000025d1d0107:0	2019-07-03 22:45:15	($Header: (1191) err=1181216 sys=0) SBL-NET-01568: Failed to read configuration parameter
SisnTcpIp	SisnSockError	1	000000025d1d0107:0	2019-07-03 22:45:15	1444185728: [SISNAPI TLS] failed to read PARAM_GENERIC_ENABLE_OPENSSL parameter
ServerLog	ServerStartup	1	000000025d1d0107:0	2019-07-03 22:45:15	Connecting to Gateway:cgw-ENT1.company.com:4330
SisnTcpIp	SisnSockError	1	000000025d1d0107:0	2019-07-03 22:45:15	1444185728: [SISNAPI TLS] failed to read PARAM_GENERIC_ENABLE_OPENSSL parameter
GenericLog	GenericError	1	000000025d1d0107:0	2019-07-03 22:45:41	(sccnmsys.cpp (1306) err=2883609 sys=0) SBL-SCC-00025: No value found in the Gateway. Default value in the repository is used.
GenericLog	GenericError	1	000000025d1d0107:0	2019-07-03 22:45:41	(sccnmsys.cpp (1306) err=2883609 sys=0) SBL-SCC-00025: No value found in the Gateway. Default value in the repository is used.
GenericLog	GenericError	1	000000025d1d0107:0	2019-07-03 22:45:41	(sccnmsys.cpp (1306) err=2883609 sys=0) SBL-SCC-00025: No value found in the Gateway. Default value in the repository is used.
GenericLog	GenericError	1	000000025d1d0107:0	2019-07-03 22:45:41	(sccnmsys.cpp (1306) err=2883609 sys=0) SBL-SCC-00025: No value found in the Gateway. Defau

**Comment by osnsergey** [comment]
srvrcfg.log:

2021 2019-07-03 21:56:58 2019-07-03 21:57:26 +0000 00000206 001 003f 0001 09 srvrcfg 663 -156072192 /siebel/ses/siebsrvr/log/srvrcfg.log 19.5.0.0 [23073] ENU
GenericLog	GenericError	1	000000025d1d0297:0	2019-07-03 21:56:58	(srscobj.cpp (2677) err=2555932 sys=0) SBL-SCM-00028: Key not found
GenericLog	GenericError	1	000000025d1d0297:0	2019-07-03 21:56:58	(sulcobj.cpp (1288) err=3407911 sys=0) SBL-SUL-00039: Could not set the param EnableCDA for config object ePharmaObjMgr_enu
GenericLog	GenericError	1	000000025d1d0297:0	2019-07-03 21:56:58	Error creating Parameter:EnableCDA for Comp:ePharmaObjMgr_enu in CompGroup:LifeSciences

GenericLog	GenericError	1	000000025d1d0297:0	2019-07-03 21:56:58	(sulcobj.cpp (1288) err=3407911 sys=0) SBL-SUL-00039: Could not set the param EnableSIFocusTracking for config object ePharmaObjMgr_enu
GenericLog	GenericError	1	000000025d1d0297:0	2019-07-03 21:56:58	Error creating Parameter:EnableSIFocusTracking for Comp:ePharmaObjMgr_enu in CompGroup:LifeSciences

**Comment by osnsergey** [comment]
srvrmgr.log

2021 2019-07-03 21:57:57 2019-07-03 21:57:57 +0000 00000004 001 003f 0001 09 srvrmgr 1078 -159918336 /siebel/ses/siebsrvr/log/srvrmgr.log 19.5.0.0 [23073] ENU
GenericLog	GenericError	1	000000025d1d0436:0	2019-07-03 21:57:57	(samisc.cpp (640) err=1313725 sys=0) SBL-SVR-03005: No server connect string for Siebel Component (null) in Siebel Enterprise (null), Siebel Server (null)
GenericLog	GenericError	1	000000025d1d0436:0	2019-07-03 21:57:57	(sccobjs.cpp (1815) err=2883590 sys=0) SBL-SCC-00006: Internal:Invalid operation.
GenericLog	GenericError	1	000000025d1d0436:0	2019-07-03 21:57:57	(srscomp.cpp (677) err=2883590 sys=0) SBL-SCC-00006: Internal:Invalid operation.

**Comment by osnsergey** [comment]
siebel.log:

2021 2019-07-03 21:56:38 2019-07-03 21:56:38 +0000 00000002 001 003f 0001 09 siebel 634 -157070720 /siebel/ses/siebsrvr/log/siebel.log 19.5.0.0 [23073] ENU
GenericLog	GenericError	1	000000025d1d027a:0	2019-07-03 21:56:38	(srvredit2.cpp (554) err=5004 sys=0) SBL-GEN-05004: Key was not found.

**Comment by OracleSiebel** [comment]
Was the system configured using the script, or did you go through this manually?
Did you make any changes to ent1.sh before launching?
   If so please share ent1.sh contents.
Can you get into srvrmgr?
   docker exec -it ses-ENT1 bash
   cd /siebel/ses/siebsrvr
   . ./siebenv.sh
   srvrmgr -g cgw-ENT1:4330 -e ENT1 -u SADMIN -p Welcome1 (unless you changed them in ent1.sh)
   list servers
Do you see the server listed?
As you see, log files are somewhat awkward within this interface. Perhaps you could post full logs to pastebin or similar?
Many of the errors you see here are actually expected errors. Can you compare them to other servers you are running in a more standard style?
You might also want to look at the SES logs in /var/lib/docker/volumes/PV/ENT1/SES/siebsrvr/enterprise/ENT1/SES/log for more clues. Is the broker working properly? Does the call center log file look OK?
What are you using for a database?

**Comment by osnsergey** [comment]
Was the system configured using the script, or did you go through this manually?
**Using script.**

Did you make any changes to ent1.sh before launching?
If so please share ent1.sh contents.

**Yes, to align with my environment.
My file content:**

>>>>>>>>>>>>>>>>>>
ROOT=/root/siebel_install/ConfiguringSiebel/Containerization/Docker/ol7/manage/scripts/automate-architecture
PV=/var/lib/docker/volumes/PV
CONTAINERBASE=registry.local.com:5000/siebel
DOMAIN=company.com
ENTERPRISE1=ENT1
DBHOST=fce-u0215
DBPORT=1521
DBINST=ORCLPDB1
TNSCONN=SIEBELDB
DOCKERNET=siebelnet
TBLO=SIEBEL
PORT=443
USER=SADMIN
PASSWD=SADMIN1
GWUSER=SADMIN
GWPASSWD=SADMIN1
ANONUSER=GUESTCST
ANONPASS=GUESTCST1
RUNASUSER=9999
ENTPROFILE=ENT
HWSERVER=localhost
COMPGRPS=callcenter,siebelwebtools,eai
SES1SERVERNAME=SES

readonly compsToManual=(
	'BusIntBatchMgr'
	'CustomAppObjMgr_enu'
	'SServiceObjMgr_enu'
	'eServiceObjMgr_enu'
	'JMSReceiver'
	'InfraEAIOutbound'
	'SMQReceiver'
	'MSMQRcvr'
	'MqSeriesSrvRcvr'
	'MqSeriesAMIRcvr'
	'JMSReceiver'
	'EIM'
	'CustomAppObjMgr_enu'
	'BusIntMgr'
	'BusIntBatchMgr'
)
<<<<<<<<<<<<<<<<<<<<<<<<<<

Can you get into srvrmgr?
docker exec -it ses-ENT1 bash
cd /siebel/ses/siebsrvr
. ./siebenv.sh
srvrmgr -g cgw-ENT1:4330 -e ENT1 -u SADMIN -p Welcome1 (unless you changed them in ent1.sh)
list servers
Do you see the server listed?

**Yes, output is below:**
**>>>>>>>>>>>>>>>>>>>>>>>>>>>**
Connecting to Gateway:cgw-ENT1.company.com:4330

Connected to 1 server(s) out of a total of 1 server(s) in the enterprise

srvrmgr> list servers

SBLSRVR_NAME  SBLSRVR_GROUP_NAME  HOST_NAME  INSTALL_DIR           SBLMGR_PID  SV_DISP_STATE  SBLSRVR_STATE  START_TIME           END_TIME  SBLSRVR_STATUS                   
------------  ------------------  ---------  --------------------  ----------  -------------  -------------  -------------------  --------  ---------------------------------
SES                               ses-ENT1   /siebel/ses/siebsrvr  263         Running        Running        2019-07-03 22:45:43            19.5.0.0 [23073] LANG_INDEPENDENT

1 row returned.
**<<<<<<<<<<<<<<<<<<<<<<<<<<<**

As you see, log files are somewhat awkward within this interface. Perhaps you could post full logs to pastebin or similar?
Many of the errors you see here are actually expected errors. Can you compare them to other servers you are running in a more standard style?

You might also want to look at the SES logs in /var/lib/docker/volumes/PV/ENT1/SES/siebsrvr/enterprise/ENT1/SES/log for more clues. Is the broker working properly? Does the call center log file look OK?

**In /var/lib/docker/volumes/PV/ENT1/SES/siebsrvr/enterprises/ENT1/SES/log I have found that:**

**2021 2019-07-03 22:50:58 0000-00-00 00:00:00 +0000 00000000 001 003f 0001 09 SWToolsObjMgr_enu 11534339 766 1463998848 /siebel/ses/siebsrvr/enterprises/ENT1/SES/log/SWToolsObjMgr_enu_0011_11534339.log 19.5.0.0 [23073] ENU
ObjMgrSRFLog	Error	1	000000025d1d02fe:0	2019-07-03 22:50:58	(objdef.cpp (565)) SBL-DAT-00388: Table 'S_RR_TABLE' defined multiple times.

Please ask your systems administrator to check your application configuration.
ObjMgrSessionLog	Error	1	000000025d1d02fe:0	2019-07-03 22:50:58	(physmod.cpp (9562)) SBL-DAT-60327: DB Patch needs to be applied to bring up the application. Please run WSRanking.exe against the DB you are launching.
ObjMgrSessionLog	Error	1	000000025d1d02fe:0	2019-07-03 22:50:58	(model.cpp (6379)) SBL-DAT-60327: DB Patch needs to be applied to bring up the application. Please run WSRanking.exe against the DB you are launching.**

**What does it mean and how to fix it?**

What are you using for a database?
Oracle 12.1.0.2

**Comment by osnsergey** [comment]
Log from /var/lib/docker/volumes/PV/ENT1/SES/cfgtoollogs/cfg
[config_07-03-2019_21.56.33.zip](https://github.com/OracleSiebel/ConfiguringSiebel/files/3361626/config_07-03-2019_21.56.33.zip)

**Comment by osnsergey** [comment]
Logs from /var/lib/docker/volumes/PV/ENT1/CGW/cfgtoollogs/cfg
[CGW.zip](https://github.com/OracleSiebel/ConfiguringSiebel/files/3361633/CGW.zip)

**Comment by OracleSiebel** [comment]
WSRanking has to be run for databases for Siebel higher than 18.6. Each month's update has instructions for this near the top of the update guide. e.g. in 19.6 https://updates.oracle.com/Orion/Services/download/p29768372_1900_MSWIN-x86-64_1of5.zip?aru=22925297&patch_file=p29768372_1900_MSWIN-x86-64_1of5.zip

**Comment by osnsergey** [comment]
That is a root cause?

**Comment by OracleSiebel** [comment]
It's the root cause of this error you reported:

DAT-60327: DB Patch needs to be applied to bring up the application. Please run WSRanking.exe against the DB you are launching.

This will prevent SES from coming up.

**Comment by osnsergey** [comment]
WSRanking is from Siebel Tools? I don't have them yet.

**Comment by osnsergey** [comment]
BTW is it possible to install Siebel DB from Siebel IP 18.8+ normally and not as upgrade?

**Comment by OracleSiebel** [comment]
At some point we also started supplying this on the server.

e.g.
docker exec -it ses-ENT1 bash
cd /siebel/ses/siebsrvr/bin/
ls WSRanking*

[root@9a55b621317c bin]# pwd
/siebel/ses/siebsrvr/bin
[root@9a55b621317c bin]# ls WSR*
WSRanking  WSRanking.dat

**Comment by OracleSiebel** [comment]
Not sure what you mean about the Siebel DB. The binaries for Siebel > 18.8 require the DB schema changes applied by WSRanking.

**Comment by osnsergey** [comment]
How to run it?
The zip you provided has only:

WSRanking.exe -s "C:\Siebel\Tools" -t SIEBEL -u SIEBEL -p ******** -o Siebel_DSN -d Oracle

Some DSN is needed, Siebel Tools again...

**Comment by OracleSiebel** [comment]
There is a DSN also on Linux. You'll need to verify it yourself. I don't have a running system at present, so you'll need to do a little digging. The command is going to look something like this:

./WSRanking -s /siebel/ses/siebsrvr -t SIEBEL -u SIEBEL -p ****** -o ENT1_DSN -d Oracle

You can verify the DSN in (forgive me if my memory is not accurate but this should help you locate it)

/var/lib/docker/volumes/PV/ENT1/SES/siebsrvr/sys/.odbc.ini

**Comment by osnsergey** [comment]
Thank you! WSRanking has worked and I've finally been able to run SES!

**Comment by OracleSiebel** [comment]
Bravo!. Welcome to the club :)

**Comment by osnsergey** [comment]
Thanks to you! :)
