### ISSUE TITLE
SES doesn't start after some time of successful work.

### ISSUE THREAD

**Issue by osnsergey** [OracleSiebel/ConfiguringSiebel#65]
Siebel server doesn't start after some time of work.
SES and SAI containers showed unhealthy status.
When I tried to stop them they seems hang and I restarted docker which also didn't restart and I had to run:

**systemctl kill docker**

then manually deleted containers and started it again (only then it 
started).

Then I run:

**bash startAll 19.01 ent1.sh**

SES can't start.

SMC shows 'Server error' when I click on any deployed component.

Is it possible to troubleshoot that somehow?

**Comment by osnsergey** [comment]
It's totally broken somehow so I decided to redeploy it again from the step where I have persistent version 19.01 and clean Siebel DB.

I have installed again 'clean' Siebel DB, removed /var/lib/docker/volumes/PV/* created those volumes again and started as bash startAll 19.01 ent1.sh.

Nothing else has changed.

**Login to SMC with default sadmin/sadmin fails...**

**Comment by osnsergey** [comment]
After saving docker images, reinstalling docker and loading images back everything has fixed. It seems some defect in docker...

**Comment by osnsergey** [comment]
Very strange behavior after docker reinstall and redeploy from saved docker images.
Siebel server it seems starts, I can login to SMC with DB user SADMIN. I can login to callcenter/enu with DB user SADMIN. But I cannot see logs in SES log folder except for SiebSrvr.log which contains errors:

[root@fce-u0233 log]# cat SiebSrvr.log
1021 2019-07-17 07:33:45 2019-07-17 07:34:42 +0000 000000b3 001 ffff 0001 09 SiebSrvr 255 1444521600 /siebel/ses/siebsrvr/log/SiebSrvr.log 19.5.0.0 [23073] ENU
SisnTcpIp       SisnSockError   1       000000025d2e00ff:0      2019-07-17 07:33:45     1444521600: [SISNAPI TLS] failed to read PARAM_GENERIC_ENABLE_OPENSSL parameter
GenericLog      GenericError    1       000000025d2e00ff:0      2019-07-17 07:33:45     ($Header: (1191) err=1181216 sys=0) SBL-NET-01568: Failed to read configuration parameter
GenericLog      GenericError    1       000000025d2e00ff:0      2019-07-17 07:33:45     ($Header: (1191) err=1181216 sys=0) SBL-NET-01568: Failed to read configuration parameter
NameServerLayerLog      Error   1       000000025d2e00ff:0      2019-07-17 07:33:45     1444521600: [cgclientservice] TLS handshake to gateway failed cgw-ENT1:4330
GenericLog      GenericError    1       000000025d2e00ff:0      2019-07-17 07:33:45     Register Service failed : NSGetZKConnectFromCG failed
GtwySvcFrmwrkLog        Error   1       000000025d2e00ff:0      2019-07-17 07:33:45     Invalid inputs provided to intiate the Registry Connection
GtwySvcFrmwrkLog        Error   1       000000025d2e00ff:0      2019-07-17 07:33:45     Connection to Registry failed
GtwySvcFrmwrkLog        Error   1       000000025d2e00ff:0      2019-07-17 07:33:45     ServiceDiscovery Exception : Unable to read CGmetafile
GtwySvcFrmwrkLog        Error   1       000000025d2e00ff:0      2019-07-17 07:33:45     Service Discovery Intialisation Failed : Registry Generic Exception
SisnTcpIp       SisnSockError   1       000000025d2e00ff:0      2019-07-17 07:34:15     1444521600: [SISNAPI TLS] failed to read PARAM_GENERIC_ENABLE_OPENSSL parameter
SisnTcpIp       SisnSockError   1       000000025d2e00ff:0      2019-07-17 07:34:15     1444521600: [SISNAPI TLS] failed to read PARAM_GENERIC_ENABLE_OPENSSL parameter
ServerLog       ServerStartup   1       000000025d2e00ff:0      2019-07-17 07:34:15     Connecting to Gateway:cgw-ENT1.company.com:4330
SisnTcpIp       SisnSockError   1       000000025d2e00ff:0      2019-07-17 07:34:15     1444521600: [SISNAPI TLS] failed to read PARAM_GENERIC_ENABLE_OPENSSL parameter
GenericLog      GenericError    1       000000025d2e00ff:0      2019-07-17 07:34:41     (sccnmsys.cpp (1306) err=2883609 sys=0) SBL-SCC-00025: No value found in the Gateway. Default value in the repository is used.

Full log is attached.
[SiebSrvr.zip](https://github.com/OracleSiebel/ConfiguringSiebel/files/3401075/SiebSrvr.zip)

**Comment by OracleSiebel** [comment]
Sorry I haven't been able to respond in detail. However, the use of the word's "saved Docker images" concerns me. You should never ever need to save the running container to a new image. Ideally you need to restart from fresh if you have issues.

**Comment by OracleSiebel** [comment]
Perhaps I misunderstood and you only saved the created images so you can re-install. You can setup a local registry to push and pull images to for this purpose rather than save/restore. Also, a rebuild is only 9 mins in any case (at least for me).

**Comment by OracleSiebel** [comment]
ses/log is typically very light on content. main log files are in siebsrvr/enterprise/...

**Comment by osnsergey** [comment]
Yes, log from siebsrvr/enterprise/... looks like fine.
What does the errors means in siebsrvr/log/SiebSrvr.log?

I have reinstalled docker and before it saved images because I then removed them to have clean docker folder. After reinstallation I lodeded them back.

**Comment by OracleSiebel** [comment]
There's no simple answer to what every error means. If you're concerned about them, it would be best to raise a standard SR in order to determine if they're an issue. It could be that they're perfectly normal. Do you have a standard (non-Docker) Siebel install to compare to?

**Comment by osnsergey** [comment]
I see. Ok, as it works it's fine now, untill we face some critical issue.
No, unfortunately I don't have anything except on Docker.

**Comment by osnsergey** [comment]
One more question, where is the documentation about REST API for the deployment? If I need to add more components.

**Comment by OracleSiebel** [comment]
That specific REST API is not documented well, if at all. The documentation amounts to the same thing you could gain simply through inspection. My advice would be to simply execute commands via SMC with the browser's network traffic recording, then reverse engineer what you need. I'd be delighted to receive pull requests for any scripts you add in this regard as there are many potentially useful additions to be made.

**Comment by osnsergey** [comment]
Understood. Thanks!

**Comment by osnsergey** [comment]
Just to write it here: 
The issue can be resolved not with docker reinstall but with removing 'siebelnet' network!

> docker network rm siebelnet

After that all containers were started and login to SCM was successful!

**Comment by OracleSiebel** [comment]
Thanks for adding your findings !
