### ISSUE TITLE
Is it possible to make additional folders persistent?

### ISSUE THREAD

**Issue by osnsergey** [OracleSiebel/ConfiguringSiebel#67]
Hello, 

In order to install SCAPI CTI communication driver we need to add to the persistence the following folders in SES container:

    /siebel/ses/siebsrvr/lib
    /siebel/ses/siebsrvr/bin

In order to deploy custom images for our custom CTI toolbar icons we need to add to the persistence the following folder in SAI container:

    /siebel/sai/applicationcontainer/webapps/siebel/images

Is it possible?

**Comment by OracleSiebel** [comment]
Hi. You can achieve both for sure.

For the first requirement, I suggest you re-apply the persistence layer after adding your customization of files and folders to:

https://github.com/OracleSiebel/ConfiguringSiebel/blob/master/Containerization/Docker/ol7/build/persistence/ses/persistenceLayerSES

For the second, I wouldn't use that solution. Instead, I already made the custom folders for SAI draw content from the persistent volumes. You can see the remapping here:

https://github.com/OracleSiebel/ConfiguringSiebel/blob/master/Containerization/Docker/ol7/build/persistence/sai/initSAI#L63

This maps siebel/images/custom to /persistent/applicationcontainer/webapps/siebel/images/custom. This should help keep delivered content separate from your custom content, thus facilitating upgrades. Similar remaps are made for custom CSS (files) and custom OpenUI code (scripts).

**Comment by osnsergey** [comment]
So, I just need to add additional folder here, like that?

readonly folderList=(
	'/applicationcontainer/logs'
	'/siebsrvr/mw/.mw'
	'/siebsrvr/bin/configdb2'
	'/cfgtoollogs'
	'/siebsrvr/log'
	'/siebsrvr/sys'
	'/siebsrvr/enterprises'
	'/siebsrvr/kwd'
	'/siebsrvr/upt'
        **'/siebsrvr/bin'**
        **'/siebsrvr/lib'**
);

rebuild SES persistent layer and that's it?

**Comment by OracleSiebel** [comment]
Actually, that sounds like a really bad idea. If you do this, you will persist the version of Siebel (i.e. the contents of siebsrvr/bin) in the siebsrvr folder. This will break your ability to update, as the key DLLs (.so) will be sourced from persistence instead of the container. If you really have something directly inside those folders (why not install elsewhere), then name them as individual files instead of persisting the entire folder.

**Comment by OracleSiebel** [comment]
In other words, persist only the driver, not the whole Siebel engine.

**Comment by OracleSiebel** [comment]
Also, thinking further, why persist the driver at all? Why not build this into the container, and automate that with each new version? If there's a file that stores the driver's configuration, that would be the item to persist.

**Comment by osnsergey** [comment]
I though about deploying the driver while starting the container but I just don't know how to do that. :) Of course that seems the best option.

**Comment by osnsergey** [comment]
I have looked into the sai container and I can't see images/custom are mapped to persistent folder, it's how it should be and it's still works?

[siebel@sai-ENT1 images]$ pwd
/siebel/sai/applicationcontainer/webapps/siebel/images
[siebel@sai-ENT1 images]$ ls custom
readme.txt
[siebel@sai-ENT1 images]$

**Comment by OracleSiebel** [comment]
Yes. I see why you're confused. You're expecting to see a symbolic link. I couldn't use that method here, as the war file can be re-unpacked at times, and that would then overwrite the symlink. So instead, the remapping is done by the automated adjustment to the server.xml file as shown above. You should be able to verify it's working as explained easily. Simply place a file in the persistent location for custom images, and then use a browser to drive to the URL where you expect it to be.

**Comment by osnsergey** [comment]
Got it, I'll check.
