### ISSUE TITLE
Error on Build command

### ISSUE THREAD

**Issue by bazzar1980** [OracleSiebel/ConfiguringSiebel#69]
Hi,
i have the following error when i run the following command:

docker build -t registry.local.com:5000/oracle/database-instantclient/32bit:12.2.0.1 --squash . 2>&1 | tee build.$(date +%F_%R).log

to build the 32-bit_instantclient_12c:

Sending build context to Docker daemon  52.37MB

Step 1/5 : FROM oraclelinux:latest
Trying to pull repository docker.io/library/oraclelinux ... 
latest: Pulling from docker.io/library/oraclelinux
04e172e76262: Pulling fs layer
04e172e76262: Verifying Checksum
04e172e76262: Download complete
04e172e76262: Pull complete
Digest: sha256:27c0c3e5ca8ce6e9ef8121c106de2d8ad28067074d7f5f5ce4e5cb78a0f07b3d
Status: Downloaded newer image for oraclelinux:latest
 ---> 5f993b1aafe5
Step 2/5 : COPY oracle-instantclient12.2-*.rpm /
 ---> 6ef6df36f612
Step 3/5 : COPY  tnsnames.ora /config/
 ---> c3aea87b3595
Step 4/5 : RUN yum -y install  ksh  tcsh  libstdc++.i686  glibc.i686  libaio.i686 && yum -y localinstall   oracle-instantclient12.2-*.i386.rpm && yum clean all && rm -rf /var/cache/yum/x86_64  && rm -rf /var/cache/yum/i686 && rm oracle-instantclient12.2*.rpm && ln -s /usr/lib/oracle/12.2/client/lib/libclntsh.so.12.1 /usr/lib/oracle/12.2/client/lib/libclntsh.so && chmod 777 /config/tnsnames.ora
 ---> Running in 7ef5774276a5
Loaded plugins: ovl, ulninfo
Resolving Dependencies
--> Running transaction check
---> Package glibc.i686 0:2.17-292.0.1.el7 will be installed
--> Processing Dependency: glibc-common = 2.17-292.0.1.el7 for package: glibc-2.17-292.0.1.el7.i686
--> Processing Dependency: libfreebl3.so for package: glibc-2.17-292.0.1.el7.i686
--> Processing Dependency: libfreebl3.so(NSSRAWHASH_3.12.3) for package: glibc-2.17-292.0.1.el7.i686
---> Package ksh.x86_64 0:20120801-139.0.1.el7 will be installed
---> Package libaio.i686 0:0.3.109-13.el7 will be installed
---> Package libstdc++.i686 0:4.8.5-39.0.1.el7 will be installed
--> Processing Dependency: libgcc_s.so.1(GCC_3.3) for package: libstdc++-4.8.5-39.0.1.el7.i686
--> Processing Dependency: libgcc_s.so.1(GCC_3.0) for package: libstdc++-4.8.5-39.0.1.el7.i686
--> Processing Dependency: libgcc_s.so.1(GCC_4.2.0) for package: libstdc++-4.8.5-39.0.1.el7.i686
--> Processing Dependency: libgcc_s.so.1 for package: libstdc++-4.8.5-39.0.1.el7.i686
--> Processing Dependency: libgcc_s.so.1(GLIBC_2.0) for package: libstdc++-4.8.5-39.0.1.el7.i686
---> Package tcsh.x86_64 0:6.18.01-15.el7 will be installed
--> Running transaction check
---> Package glibc-common.x86_64 0:2.17-260.0.17.el7_6.6 will be updated
--> Processing Dependency: glibc-common = 2.17-260.0.17.el7_6.6 for package: glibc-2.17-260.0.17.el7_6.6.x86_64
---> Package glibc-common.x86_64 0:2.17-292.0.1.el7 will be an update
---> Package libgcc.x86_64 0:4.8.5-36.0.1.el7_6.2 will be updated
---> Package libgcc.i686 0:4.8.5-39.0.1.el7 will be installed
---> Package libgcc.x86_64 0:4.8.5-39.0.1.el7 will be an update
---> Package nss-softokn-freebl.x86_64 0:3.36.0-5.0.1.el7_5 will be updated
---> Package nss-softokn-freebl.i686 0:3.44.0-5.0.1.el7 will be installed
--> Processing Dependency: nss-util >= 3.44.0-3 for package: nss-softokn-freebl-3.44.0-5.0.1.el7.i686
--> Processing Dependency: nspr >= 4.21.0 for package: nss-softokn-freebl-3.44.0-5.0.1.el7.i686
---> Package nss-softokn-freebl.x86_64 0:3.44.0-5.0.1.el7 will be an update
--> Running transaction check
---> Package glibc.x86_64 0:2.17-260.0.17.el7_6.6 will be updated
---> Package glibc.x86_64 0:2.17-292.0.1.el7 will be an update
---> Package nspr.x86_64 0:4.19.0-1.el7_5 will be updated
---> Package nspr.x86_64 0:4.21.0-1.el7 will be an update
---> Package nss-util.x86_64 0:3.36.0-1.1.el7_6 will be updated
---> Package nss-util.x86_64 0:3.44.0-3.el7 will be an update
--> Finished Dependency Resolution
[91mError:  Multilib version problems found. This often means that the root
       cause is something else and multilib version checking is just
       pointing out that there is a problem. Eg.:
       
         1. You have an upgrade for libstdc++ which is missing some
            dependency that another package requires. Yum is trying to
            solve this by installing an older version of libstdc++ of the
            different architecture. If you exclude the bad architecture
            yum will tell you what the root cause is (which package
            requires what). You can try redoing the upgrade with
            --exclude libstdc++.otherarch ... this should give you an error
            message showing the root cause of the problem.
       
         2. You have multiple architectures of libstdc++ installed, but
            yum can only see an upgrade for one of those architectures.
            If you don't want/need both architectures anymore then you
            can remove the one with the missing update and everything
            will work.
       
         3. You have duplicate versions of libstdc++ installed already.
            You can use "yum check" to get yum show these errors.
       
       ...you can also use --setopt=protected_multilib=false to remove
       this checking, however this is almost never the correct thing to
       do as something else is very likely to go wrong (often causing
       much more problems).
       
       Protected multilib versions: libstdc++-4.8.5-39.0.1.el7.i686 != libstdc++-4.8.5-36.0.1.el7_6.2.x86_64
[0mThe command '/bin/sh -c yum -y install  ksh  tcsh  libstdc++.i686  glibc.i686  libaio.i686 && yum -y localinstall   oracle-instantclient12.2-*.i386.rpm && yum clean all && rm -rf /var/cache/yum/x86_64  && rm -rf /var/cache/yum/i686 && rm oracle-instantclient12.2*.rpm && ln -s /usr/lib/oracle/12.2/client/lib/libclntsh.so.12.1 /usr/lib/oracle/12.2/client/lib/libclntsh.so && chmod 777 /config/tnsnames.ora' returned a non-zero code: 1

How i can solve it?

**Comment by spolepally** [comment]
Please see below 
https://github.com/OracleSiebel/ConfiguringSiebel/issues/56#issuecomment-476242344

**Comment by bazzar1980** [comment]
Ok, sorry but i'm newest of docker so how i have to do this, can you tell me the steps?

**Comment by spolepally** [comment]
Remove libstdc++.i686 library from below dockerfile and execute docker build
https://github.com/OracleSiebel/ConfiguringSiebel/blob/69b713c7077a066e7457238efd9d674f0c6fe52e/Containerization/Docker/ol7/build/32-bit_instantclient_12c/dockerfile#L13
