### ISSUE TITLE
Custom component Groups & component

### ISSUE THREAD

**Issue by SriJaganath** [OracleSiebel/ConfiguringSiebel#88]
Hi Duncan,
While configuring Siebel server in docker setup, need to create custom component groups & custom components.
can we make it possible while deploying the profile referring those custom component groups?

Appreciate your response.
Thanks & Regards,
SriJ

**Comment by OracleSiebel** [comment]
If you can do it using SMC, then you can observe the JSON using a browser's developer tools. If not, then you've got to pick apart common.scm and experiment with that. Neither area has any documentation to support you, so you're on your own. common.scm will likely never be documented, but the REST API for SMC should eventually get documented. In a nutshell, it's possible, but will be hard work.

**Comment by SriJaganath** [comment]
Thanks for the update, let me work on it . Please allow sometime, will update with the findings

**Comment by OracleSiebel** [comment]
Closing. If you wish to continue, please re-open.
