### ISSUE TITLE
Docker image for Document Server

### ISSUE THREAD

**Issue by SriJaganath** [OracleSiebel/ConfiguringSiebel#89]
Hi Duncan,
How to build docker image for Document server?
What is the base image that can be used?
Appreciate your guidance to build it.
Thanks & Regards,
SriJ

**Comment by OracleSiebel** [comment]
Document Server is Windows only. You don't need to create a container version though; you can use a standard install and add that server to the Enterprise via SMC. We haven't done enough testing with our Windows container for me to get feel comfortable putting you on that path as I cannot provide support if something goes wrong.
