### ISSUE TITLE
How to avoid certification errors while accessing from host redirected port?

### ISSUE THREAD

**Issue by SriJaganath** [OracleSiebel/ConfiguringSiebel#91]
Hi Duncan,
While trying to access AI https port with host mapped port, it is giving certification errors.
Could you please let me how can we avoid such errors. 
Appreciate your response.

Thanks in advance

Thanks & Regards,
SriJ

**Comment by OracleSiebel** [comment]
I think the bottom line is that you need to add the certificate authority that you self signed into the trust chain of your browser. I can only help on this topic in the same way you can help yourself with Google. This was my first hit - https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate. The process will be slightly different for every browser. To avoid this completely, the alternative is to pay for a certificate signed by a 'real' certifciate authority, which will then already be in the trust list for your browser.

**Comment by SriJaganath** [comment]
Earlier, without Docker, In our case we are using host specific CA authorized certificate for all the hosts like AI, gateway & all Siebel app servers, so when we try to access each host using https port , we do get cert errors.

So we used the same CA authorized certificate, not self signed, for one of the AI host but while trying to access from Docker host redirected port it is still giving the certificate error, as the hostname of the AI cert file is not matching with the docker host name.

So, how to overcome such errors?

**Comment by OracleSiebel** [comment]
Ultimately, you probably need to arrange for DNS to deliver the correct host name for the certificate to the machine acting as the SAI host. You should be able to test this locally by editing your 'hosts' file. There's no workaround as such. You just need to line up everything correctly. The alternative is to use wildcard certificates.

**Comment by SriJaganath** [comment]
sorry to say that as per our Organization policy we can't use wildcard certs.
In the present scenario my SAI host name is sai-dev.<mydomain>.com, so got the CA authorized certificate for the same host "sai-dev.<mydomain>.com".
If this is not a docker, in this scenario access directly https://sai-dev.<mydomain>.com:9001 will not throw any error since it is CA auth cert  whereas now in the case of Docker I can't access directly that URL instead I will user Docker host (docker-host.<mydomain>.com) and Docker redirected port (8001), so it should be accessed from browser like this https://docker-host.<mydomain>.com:8001.  
In this case as SAI host specific CA cert is not matching with Docker host name, so it is throwing the cert error.

What is the approach we have to take in these scenario?

**Comment by OracleSiebel** [comment]
It should be as simple as ensuring that the ip address of docker-host can be resolved using sai-dev.

**Comment by SriJaganath** [comment]
I didn't get what do you mean by "ip address of docker-host can be resolved using sai-dev".
In the demo youtube video as well @1:19:50 while you are trying to access AI SMC using host name, localhost, getting not secure error. 
So what I am saying is even if we use CA auth certs for SAI, that certificate is for SAI host name not for Docker host so It won't match the certificate of SAI host name.
How to overcome this

**Comment by OracleSiebel** [comment]
In the demo video, I am using a self-signed certificate, so I will always get the security warning. That's expected.
For you, you need to ensure that the certificate lines up with the name of the server you're accessing.

So let's say you have a certificate for sai-dev.company.com signed by Verisign. Verisign is already trusted as a CA by your browser, and it's vertifying that sai-dev.company.com is a valid host for your certificate.

You have a machine running the docker containers on 10.0.0.1. DNS resolves docker-host as 10.0.0.1. On that machine you have your container for SAI exposed on port 9001. As a result your browser can go to docker-host:9001 to access Tomcat running on the SAI machine. When the certificate comes back, the browser checks the certificate and finds the the certificate is for sai-dev.company.com, but you're accessing it using docker-host.company.com. This generates the error.

If you edit the hosts file on your machine you can add the following line

10.0.0.1  sai-dev

Now, when your browser requests to go to https://sai-dev:9001, you will be directed to the docker host machine. WHen the response comes back, the certificate should match the domain name and the browser should stop generating an error.

**Comment by SriJaganath** [comment]
let me try this, and post my observation

**Comment by OracleSiebel** [comment]
I'll assume you resolved this. Please re-open if necessary.
