### ISSUE TITLE
LDAP search 

### ISSUE THREAD

**Issue by SriJaganath** [OracleSiebel/ConfiguringSiebel#92]
Hi Duncan,
The base rpm to install Oracle client doesn't have ldapbind & ldapsearch.
Could you please let us how to test ldapsearch, do we need to install any rpm's for this and also do we require to these binaries to make Siebel ldap to be work.

Appreciate your response.
Thanks in advance

Thanks & Regards,
SriJ

**Comment by OracleSiebel** [comment]
Could you be more specific about what you're trying to achieve?

**Comment by SriJaganath** [comment]
Created the wallet and need to check ldapsearch & ldapbind are working with the created wallet

**Comment by OracleSiebel** [comment]
I'm sorry - what wallet? I have no experience with ldap, so I'll struggle to help unless you're totally specific about the whole process.

**Comment by SriJaganath** [comment]
while setting up Siebel LDAP profile,  one of the parameters need to provide is "SslDatabase", which is a Wallet location, and another parameter is "WalletPassword" . wallet contains signed certificates to be created using "orapki" utility.

**Comment by OracleSiebel** [comment]
What do you normally install in order to gain access to ldapbind and ldapsearch, if those are the commands required? Have you tried installing a full Oracle client instead of the instantclient? You need to resolve that part of the challenge first. As it's not related to Siebel, I can't provide guidance. Once you know the answer, you'll need to adapt the example dockerfiles found here so that the required additional packages are installed.

**Comment by OracleSiebel** [comment]
ldapsearch and other client commands can be added to the container by adding to the list of packages to be installed here:

https://github.com/OracleSiebel/ConfiguringSiebel/blob/master/Containerization/Docker/ol7/build/base_siebel/ses/dockerfile#L16

After adding openldap openldap-clients, ldapsearch becomes available

bash-4.2# ldapsearch
ldap_sasl_interactive_bind_s: Can't contact LDAP server (-1)

**Comment by SriJaganath** [comment]
I have used Oracle Client for LDAP instead of Oracle client RPM's to install base image, with that I am getting just 2.5 GB as base image size so thought of checking are there any RPM's of Oracle to setup instead of Oracle Client for LDAP binaries.
As per Oracle documentation for LDAP Oracle Client for LDAP only supports not Openldap rpm's

**Comment by OracleSiebel** [comment]
I see. So it's the size of the full client that is the main concern? I don't have any way to answer your question. Can you submit an SR via MOS perhaps? You might then be able to get a response from the DB team.

If you can establish the smallest amount of files required to run the commands you need, you should then be able to delete everything else. You could adopt a multistage build process to optimize the final file size, or see if squash will shrink the container.

**Comment by SriJaganath** [comment]
you are right sir, my concern was size. with that base when I build SES image has come more than 5+ GB.
So, thought of checking, in Oracle Siebel, are you using any extra RPM to install/support LDAP client?

Even I tried squash while building the image but it didn't help much.

**Comment by OracleSiebel** [comment]
It seems the only thing you're missing are the tools you're looking for to test verification and wallet manipulation. The siebel server is already equipped to connect to the LDAP server and to utilise a valid wallet file.
We'll address this for our pre-installed containers in the near future by customizing the instant client prior to installation. As a result, future SES containers will include the tools you seek. This doesn't help you move forward right now as you're building your own container, but there are still a few options you have to move forward:

1. You could modify your dockerfile to copy in the executables you need during build time. If you do this in a step after the instant client installation, you can copy ldapbind, ldapsearch, orapki and other tools to the client bin directory. Be sure to adjust ownership and file flags appropriately
2. You could utilise the hotfix folder to copy the missing executables during container startup. This will copy them into the /siebel folder, but they could be anywhere you like there. The executables will find the necessary libraries on LD_LIBRARY_PATH
3. You could just use docker cp to copy the executables in to the container when you need them.
4. You could create your own custom RPM for instant-client-tools. I put this last as it's the hardest. I can't support you with that.
