### ISSUE TITLE
Missing folders in AI

### ISSUE THREAD

**Issue by sunkugupta** [OracleSiebel/ConfiguringSiebel#94]
Hello Duncan,

We observe that the siebel installer is Not installing some folders and files for AI. We do Not see folders like "smc"  and files like default.htm. Due to this the AI docker is failing to run.

Please advice. 

Thanks
Sunku

**Comment by OracleSiebel** [comment]
Let's start with a little more detail. Which version are you trying to prepare? Are you using exactly the rsp files given here or have you modified them to install other languages? The base and update processes should have created logs if you followed the process; can you post those into this issue please.

My guess is that there's some sort of issue during war file deployment. The process has specific pauses to allow the war files to deploy:

https://github.com/OracleSiebel/ConfiguringSiebel/blob/master/Containerization/Docker/ol7/build/base_siebel/sai/dockerfile#L26
https://github.com/OracleSiebel/ConfiguringSiebel/blob/master/Containerization/Docker/ol7/build/update/sai/dockerfile#L12

If your hardware is particularly slow, it's possible these pauses are not enough. In such a situation, it may be possible to force re-deployment directly from the war file by following this sort of process manually inside the running container:

docker exec -it <sai-container>  bash
cd /siebel/sai/applicationcontainer/bin
./shutdown.sh
cd /siebel/sai/applicationcontainer/webapps
rm -rf siebel
cd /siebel/sai/applicationcontainer/bin
./startup.sh

This should result in a full redeployment of the war file. This is probably the first thing to test, and after that, try to figure out why the war didn't fully deploy during the install. If necessary, add more time to the pause.

Hope this helps.

**Comment by sunkugupta** [comment]
You were right. I increased the sleep to 360 and it worked!! thanks

**Comment by OracleSiebel** [comment]
Thanks for closing the loop !
