### ISSUE TITLE
Object Managers are in Not Online status

### ISSUE THREAD

**Issue by sunkugupta** [OracleSiebel/ConfiguringSiebel#97]
Hello,

The object managers failed to start. They remain in "Not Online" status. Siebel server is up. I can also connect fine with srvrmgr. However, for some reason, the object managers remain in "Not Online" status. 

Appreciate your help.

Thanks
Sunku

**Comment by sunkugupta** [comment]
Hey Duncan,

Can you please check on this. Thanks

**Comment by duncanford** [comment]
Hi Sunku,

You're not really telling me very much here. How did you build? What version are you using? What database are you using? How did you initialise the database? What operating system?

Please provide some more details and I'll see if there's anything I can do to help.

**Comment by OracleSiebel** [comment]
Closing as no further details given. Please re-open if still stuck.
