### ISSUE TITLE
Other language than ENU?

### ISSUE THREAD

**Issue by dhiriart** [OracleSiebel/ConfiguringSiebel#98]
Can we deploy a SES docker image with ESN callcenter component?
Regards

**Comment by duncanford** [comment]
Yes. You'll need to build that language into your containers by adjusting the rsp files for each build; e.g.

https://github.com/OracleSiebel/ConfiguringSiebel/blob/master/Containerization/Docker/ol7/build/base_siebel/ses/ses.rsp#L28

**Comment by dhiriart** [comment]
Great... I assume that the key value will be "Spanish" and not "ESN" (or "ESP")

Thank you Duncan...

**Comment by duncanford** [comment]
I think you're right, but I'm not certain. The way to be certain is to run the standard installer and save the results to an rsp file to check. There may be more than one Spanish variant.

**Comment by dhiriart** [comment]
I will try like this, as I get from rsp file....  
...
b_isApplicationInterfaceInstalled="false"
b_isEnterpriseCacheInstalled="false"
b_isConstraintEngineInstalled="false"
**selectedLangs="[English, Spanish]"**
s_Httpport="8080"
s_Shutdownport="8005"
s_Redirectport="8443"
...

Thanks

**Comment by OracleSiebel** [comment]
I'll assume you managed to move forward with this. Please re-open if not.
